######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 4 21:38:52 2008
######################################################################

TARGET = einkfb
include(../../qpluginbase.pri)

DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += eink_screen.h
SOURCES += eink_screen.cpp eink_screen_driver.cpp 
