#!/bin/sh -e

case "$1" in
    start)
        echo > /proc/sys/kernel/hotplug
        
        mount -n -o mode=0755 -t tmpfs tmpfs /dev

        # Create static device nodes in /dev
        mknod /dev/console c 5 1
        mknod /dev/null c 1 3
        
        echo "Starting the hotplug events dispatcher udevd"
        udevd --daemon

        echo "Synthesizing initial hotplug events"
        udevtrigger
        udevsettle --timeout=300
        ;;
    stop)
        ;;
    restart|force-reload)
        /opt/freescale/ltib/tmp/rpm-tmp.96339 stop
        /opt/freescale/ltib/tmp/rpm-tmp.96339 start
        ;;
    *)
        echo "Usage: /etc/init.d/udev {start|stop|restart|force-reload}"
	echo 
        exit 1
        ;;
esac

exit 0

