task :default => :build

def has_distcc
  if ENV['DISABLE_DISTCC']
    false
  else
    system("which distcc")
  end
end

def has_ccache
  system('which ccache')
end

def compiler_prefix
  if has_ccache
    "ccache"
  elsif has_distcc
    "distcc"
  else
    ""
  end
end

def cmake_cmd(arch)
  arm_cc = "/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-linux-gcc"
  arm_cxx = "/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-linux-g++"
  if arch == :arm
    "CC='#{compiler_prefix} #{arm_cc}' CXX='#{compiler_prefix} #{arm_cxx}' cmake "
  elsif arch == :x86
    "CC='#{compiler_prefix} gcc' CXX='#{compiler_prefix} g++' cmake "
  else
    raise "Invalid machine type: #{arch}"
  end
end

def make_cmd
  if has_distcc
    "make -j18"
  else
    "make -j2"
  end
end

desc "Clean up build artifacts"
task :clean do
  sh 'rm -rf build'  # Remove compilation targets and cmake output.
end

directory "build/arm"
directory "build/x86"

namespace :config do
  task :shared_env do
    if has_distcc
      ENV['CCACHE_PREFIX'] = 'distcc'
    end
  end

  task :arm_env do
    path = ENV['PATH']
    ENV['PATH'] = "/opt/onyx/arm/bin:/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/:#{path}"
  end

  task :x86 => ["build/x86", :shared_env] do
    sh "cd build/x86 && #{cmake_cmd :x86} ../.."
  end

  task :arm => ["build/arm", :shared_env, :arm_env] do
    sh "cd build/arm && #{cmake_cmd :arm} -DBUILD_FOR_ARM:BOOL=ON ../.."
  end
end

namespace :build do
  [:x86, :arm].each do |arch|
    desc "Build feed_reader (#{arch})"
    task arch => "config:#{arch}" do
      sh "cd build/#{arch} && #{make_cmd}"
    end
  end
end

desc "build:x86"
task :build => "build:x86"

desc "Run all tests."
task :test => :build do
  sh "killall -q -9 Xvfb || true"
  sh "cd build/x86 && xvfb-run -a -w 3 make test"
end
