<!-- auto-generated by ./tsv2ts.pl from picseledit.csv on Thu Sep 24 14:15:51 2009 -->

<!-- Copyright (C) Picsel, 2007. All Rights Reserved. -->

<!-- @author Picsel Technologies Ltd -->

<!-- $Id: picseledit-en-gb.ts,v 1.19 2009/09/28 10:46:59 neilk Exp $ -->

<!DOCTYPE TS><TS>
<context>
    <name>ContentsEditDialog</name>
    <message>
        <source>RES_CED_Brazil</source>
        <translation>Brazil</translation>
    </message>
    <message>
        <source>RES_CED_Uruguay</source>
        <translation>Uruguay</translation>
    </message>
    <message>
        <source>RES_CED_Argentina</source>
        <translation>Argentina</translation>
    </message>
    <message>
        <source>RES_CED_Colombia</source>
        <translation>Colombia</translation>
    </message>
    <message>
        <source>RES_CED_Guatemala</source>
        <translation>Guatemala</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia</source>
        <translation>Bolivia</translation>
    </message>
    <message>
        <source>RES_CED_Chile</source>
        <translation>Chile</translation>
    </message>
    <message>
        <source>RES_CED_DominicanRepublic</source>
        <translation>Dominican Republic</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador</source>
        <translation>Ecuador</translation>
    </message>
    <message>
        <source>RES_CED_Mexico</source>
        <translation>Mexico</translation>
    </message>
    <message>
        <source>RES_CED_Peru</source>
        <translation>Peru</translation>
    </message>
    <message>
        <source>RES_CED_Paraguay</source>
        <translation>Paraguay</translation>
    </message>
    <message>
        <source>RES_CED_ElSalvador</source>
        <translation>El Salvador</translation>
    </message>
    <message>
        <source>RES_CED_TrinidadTobago</source>
        <translation>Trinidad &amp; Tobago</translation>
    </message>
    <message>
        <source>RES_CED_Honduras</source>
        <translation>Honduras</translation>
    </message>
    <message>
        <source>RES_CED_Nicaragua</source>
        <translation>Nicaragua</translation>
    </message>
    <message>
        <source>RES_CED_Venezuela</source>
        <translation>Venezuela</translation>
    </message>
    <message>
        <source>RES_CED_Panama</source>
        <translation>Panama</translation>
    </message>
    <message>
        <source>RES_CED_CostaRica</source>
        <translation>Costa Rica</translation>
    </message>
    <message>
        <source>RES_CED_Jamaica</source>
        <translation>Jamaica</translation>
    </message>
    <message>
        <source>RES_CED_FrenchCanada</source>
        <translation>French Canada</translation>
    </message>
    <message>
        <source>RES_CED_UnitedKingdom</source>
        <translation>United Kingdom</translation>
    </message>
    <message>
        <source>RES_CED_UnitedStates</source>
        <translation>United States</translation>
    </message>
    <message>
        <source>RES_CED_ISO</source>
        <translation>ISO</translation>
    </message>
    <message>
        <source>RES_CED_Local</source>
        <translation>Local</translation>
    </message>
    <message>
        <source>RES_CED_HongKong</source>
        <translation>Hong Kong</translation>
    </message>
    <message>
        <source>RES_CED_Taiwan</source>
        <translation>Taiwan</translation>
    </message>
    <message>
        <source>RES_CED_Indonesia</source>
        <translation>Indonesia</translation>
    </message>
    <message>
        <source>RES_CED_Malaysia</source>
        <translation>Malaysia</translation>
    </message>
    <message>
        <source>RES_CED_Philippines</source>
        <translation>Philippines</translation>
    </message>
    <message>
        <source>RES_CED_Thailand</source>
        <translation>Thailand</translation>
    </message>
    <message>
        <source>RES_CED_Vietnam</source>
        <translation>Vietnam</translation>
    </message>
    <message>
        <source>RES_CED_Brazil_Real</source>
        <translation>Brazil : Real</translation>
    </message>
    <message>
        <source>RES_CED_Uruguay_Peso</source>
        <translation>Uruguay : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Argentina_Peso</source>
        <translation>Argentina : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Colombia_Peso</source>
        <translation>Colombia : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Guatemala_Quetzal</source>
        <translation>Guatemala : Quetzal</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia_Boliviano_Quechua</source>
        <translation>Bolivia : Boliviano (Quechua)</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia_Boliviano_Spanish</source>
        <translation>Bolivia : Boliviano (Spanish)</translation>
    </message>
    <message>
        <source>RES_CED_Chile_Peso</source>
        <translation>Chile : Peso</translation>
    </message>
    <message>
        <source>RES_CED_DominicanRepublic_Peso</source>
        <translation>Dominican Republic : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador_Sucre_Quechua</source>
        <translation>Ecuador : Sucre (Quechua)</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador_Sucre_Spanish</source>
        <translation>Ecuador : Sucre (Spanish)</translation>
    </message>
    <message>
        <source>RES_CED_Mexico_Peso</source>
        <translation>Mexico : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Peru_NuevoSol_Quechua</source>
        <translation>Peru : Nuevo Sol (Quechua)</translation>
    </message>
    <message>
        <source>RES_CED_Peru_NuevoSol_Spanish</source>
        <translation>Peru : Nuevo Sol (Spanish)</translation>
    </message>
    <message>
        <source>RES_CED_Paraguay_Guarani</source>
        <translation>Paraguay : Guarani</translation>
    </message>
    <message>
        <source>RES_CED_ElSalvador_Colon</source>
        <translation>El Salvador : Colon</translation>
    </message>
    <message>
        <source>RES_CED_TrinidadTobago_Dollar</source>
        <translation>Trinidad &amp; Tobago : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Honduras_Lempira</source>
        <translation>Honduras : Lempira</translation>
    </message>
    <message>
        <source>RES_CED_Nicaragua_Cordoba</source>
        <translation>Nicaragua : Cordoba</translation>
    </message>
    <message>
        <source>RES_CED_Venezuela_Bolivar</source>
        <translation>Venezuela : Bolivar</translation>
    </message>
    <message>
        <source>RES_CED_Panama_Balboa</source>
        <translation>Panama : Balboa</translation>
    </message>
    <message>
        <source>RES_CED_CostaRica_Colon</source>
        <translation>Costa Rica : Colon</translation>
    </message>
    <message>
        <source>RES_CED_Jamaica_Dollar</source>
        <translation>Jamaica : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_FrenchCanada_Dollar</source>
        <translation>French Canada : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Sterling</source>
        <translation>Sterling</translation>
    </message>
    <message>
        <source>RES_CED_UnitedKingdom_Pound</source>
        <translation>United Kingdom : Pound</translation>
    </message>
    <message>
        <source>RES_CED_UnitedStates_Dollar</source>
        <translation>United States : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Euro</source>
        <translation>Euro</translation>
    </message>
    <message>
        <source>RES_CED_Euro_Alt</source>
        <translation>Euro (Alt)</translation>
    </message>
    <message>
        <source>RES_CED_HongKong_Dollar</source>
        <translation>Hong Kong : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Taiwan_Dollar</source>
        <translation>Taiwan : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Indonesia_Rupiah</source>
        <translation>Indonesia : Rupiah</translation>
    </message>
    <message>
        <source>RES_CED_Malaysia_Ringgit</source>
        <translation>Malaysia : Ringgit</translation>
    </message>
    <message>
        <source>RES_CED_Philippines_Peso</source>
        <translation>Philippines : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Thailand_Baht</source>
        <translation>Thailand : Baht</translation>
    </message>
    <message>
        <source>RES_CED_Vietnam_Dong</source>
        <translation>Vietnam : Dong</translation>
    </message>
    <message>
        <source>RES_CED_Brazil_Real_Name</source>
        <translation>Brazil : Real (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Uruguay_Peso_Name</source>
        <translation>Uruguay : Peso (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Argentina_Peso_Name</source>
        <translation>Argentina : Peso (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Colombia_Peso_Name</source>
        <translation>Colombia : Peso (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Guatemala_Quetzal_Name</source>
        <translation>Guatemala : Quetzal (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia_Boliviano_Name</source>
        <translation>Bolivia : Boliviano (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Chile_Peso_Name</source>
        <translation>Chile : Peso (Name)</translation>
    </message>
    <message>
        <source>RES_CED_DominicanRepublic_Peso_Name</source>
        <translation>Dominican Republic : Peso (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador_Sucre_Name</source>
        <translation>Ecuador : Sucre (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Mexico_Peso_Name</source>
        <translation>Mexico : Peso (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Peru_NuevoSol_Name</source>
        <translation>Peru : Nuevo Sol (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Paraguay_Guarani_Name</source>
        <translation>Paraguay : Guarani (Name)</translation>
    </message>
    <message>
        <source>RES_CED_ElSalvador_Colon_Name</source>
        <translation>ElSalvador : Colon (Name)</translation>
    </message>
    <message>
        <source>RES_CED_TrinidadTobago_Dollar_Name</source>
        <translation>Trinidad &amp; Tobago : Dollar (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Honduras_Lempira_Name</source>
        <translation>Honduras : Lempira (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Nicaragua_Cordoba_Name</source>
        <translation>Nicaragua : Cordoba (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Venezuela_Bolivar_Name</source>
        <translation>Venezuela : Bolivar (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Panama_Balboa_Name</source>
        <translation>Panama : Balboa (Name)</translation>
    </message>
    <message>
        <source>RES_CED_CostaRica_Colon_Name</source>
        <translation>Costa Rica : Colon (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Haiti_Gourde_Name</source>
        <translation>Haiti : Gourde (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Jamaica_Dollar_Name</source>
        <translation>Jamaica : Dollar (Name)</translation>
    </message>
    <message>
        <source>RES_CED_UnitedKingdom_Pound_Name</source>
        <translation>United Kingdom : Pound (Name)</translation>
    </message>
    <message>
        <source>RES_CED_UnitedStates_Dollar_Name</source>
        <translation>United States : Dollar (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Euro_Name</source>
        <translation>Euro (Name)</translation>
    </message>
    <message>
        <source>RES_CED_HongKong_Dollar_Name</source>
        <translation>Hong Kong : Dollar (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Taiwan_Dollar_Name</source>
        <translation>Taiwan : Dollar (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Indonesia_Rupiah_Name</source>
        <translation>Indonesia : Rupiah (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Malaysia_Ringgit_Name</source>
        <translation>Malaysia : Ringgit (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Philippines_Peso_Name</source>
        <translation>Philippines : Peso (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Thailand_Baht_Name</source>
        <translation>Thailand : Baht (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Vietnam_Dong_Name</source>
        <translation>Vietnam : Dong (Name)</translation>
    </message>
    <message>
        <source>RES_CED_NEG1</source>
        <translation>Use -ve sign</translation>
    </message>
    <message>
        <source>RES_CED_NEG2</source>
        <translation>No -ve sign, Red</translation>
    </message>
    <message>
        <source>RES_CED_NEG3</source>
        <translation>Use -ve sign, indent</translation>
    </message>
    <message>
        <source>RES_CED_NEG4</source>
        <translation>Use -ve sign, Red, indent</translation>
    </message>
    <message>
        <source>RES_CED_DP0</source>
        <translation>No decimal places</translation>
    </message>
    <message>
        <source>RES_CED_DP1</source>
        <translation>One decimal place</translation>
    </message>
    <message>
        <source>RES_CED_DP2</source>
        <translation>Two decimal places</translation>
    </message>
    <message>
        <source>RES_CED_DP3</source>
        <translation>Three decimal places</translation>
    </message>
    <message>
        <source>RES_CED_DP10</source>
        <translation>Ten decimal places</translation>
    </message>
    <message>
        <source>RES_CED_NOCOMMAS</source>
        <translation>No commas</translation>
    </message>
    <message>
        <source>RES_CED_COMMAS</source>
        <translation>Commas</translation>
    </message>
    <message>
        <source>RES_CED_LONGDATEFORMAT</source>
        <translation>Formal Date</translation>
    </message>
    <message>
        <source>RES_CED_DATEFORMAT</source>
        <translation>Date</translation>
    </message>
    <message>
        <source>RES_CED_TIMEFORMAT</source>
        <translation>Time</translation>
    </message>
    <message>
        <source>RES_CED_DATETIMEFORMAT</source>
        <translation>Date and Time</translation>
    </message>
    <message>
        <source>RES_CED_FRAC1</source>
        <translation>Up to One digit</translation>
    </message>
    <message>
        <source>RES_CED_FRAC2</source>
        <translation>Up to Two digits</translation>
    </message>
    <message>
        <source>RES_CED_FRAC3</source>
        <translation>Up to Three digits</translation>
    </message>
    <message>
        <source>RES_CED_FRAC4</source>
        <translation>As Halves</translation>
    </message>
    <message>
        <source>RES_CED_FRAC5</source>
        <translation>As Quarters</translation>
    </message>
    <message>
        <source>RES_CED_FRAC6</source>
        <translation>As Eighths</translation>
    </message>
    <message>
        <source>RES_CED_FRAC7</source>
        <translation>As Sixteenths</translation>
    </message>
    <message>
        <source>RES_CED_FRAC8</source>
        <translation>As Tenths</translation>
    </message>
    <message>
        <source>RES_CED_FRAC9</source>
        <translation>As Hundredths</translation>
    </message>
    <message>
        <source>RES_CED_GENERAL</source>
        <translation>General</translation>
    </message>
    <message>
        <source>RES_CED_NUMBER</source>
        <translation>Number</translation>
    </message>
    <message>
        <source>RES_CED_CURRENCY</source>
        <translation>Currency</translation>
    </message>
    <message>
        <source>RES_CED_ACCOUNTING</source>
        <translation>Accounting</translation>
    </message>
    <message>
        <source>RES_CED_DATE</source>
        <translation>Date</translation>
    </message>
    <message>
        <source>RES_CED_TIME</source>
        <translation>Time</translation>
    </message>
    <message>
        <source>RES_CED_PERCENTAGE</source>
        <translation>Percentage</translation>
    </message>
    <message>
        <source>RES_CED_FRACTION</source>
        <translation>Fraction</translation>
    </message>
    <message>
        <source>RES_CED_SCIENTIFIC</source>
        <translation>Scientific</translation>
    </message>
    <message>
        <source>RES_CED_TEXT</source>
        <translation>Text</translation>
    </message>
    <message>
        <source>RES_CED_CUSTOM</source>
        <translation>Custom</translation>
    </message>
    <message>
        <source>RES_CED_NOACTION</source>
        <translation>No action</translation>
    </message>
    <message>
        <source>RES_CED_INSERTROWBEFORE</source>
        <translation>Insert row before</translation>
    </message>
    <message>
        <source>RES_CED_INSERTCOLUMNBEFORE</source>
        <translation>Insert column before</translation>
    </message>
    <message>
        <source>RES_CED_INSERTTABLE</source>
        <translation>Insert Table</translation>
    </message>
    <message>
        <source>RES_CED_DELETECURRENTROW</source>
        <translation>Delete current row</translation>
    </message>
    <message>
        <source>RES_CED_DELETECURRENTCOLUMN</source>
        <translation>Delete current column</translation>
    </message>
    <message>
        <source>RES_CED_DELETETABLE</source>
        <translation>Delete table</translation>
    </message>
    <message>
        <source>RES_CED_TITLE</source>
        <translation>Edit </translation>
    </message>
    <message>
        <source>RES_CED_REPLACE</source>
        <translation>Replace</translation>
    </message>
    <message>
        <source>RES_CED_INSERTABOVE</source>
        <translation>Insert Above</translation>
    </message>
    <message>
        <source>RES_CED_INSERTBELOW</source>
        <translation>Insert Below</translation>
    </message>
    <message>
        <source>RES_CED_STYLE</source>
        <translation>Style:</translation>
    </message>
    <message>
        <source>RES_CED_SIZE</source>
        <translation>Size:</translation>
    </message>
    <message>
        <source>RES_CED_COLOUR</source>
        <translation>Colour:</translation>
    </message>
    <message>
        <source>RES_CED_HIGHLIGHT</source>
        <translation>Highlight:</translation>
    </message>
    <message>
        <source>RES_CED_FONT</source>
        <translation>Font:</translation>
    </message>
    <message>
        <source>RES_CED_FORMAT</source>
        <translation>Format:</translation>
    </message>
    <message>
        <source>RES_CED_RESIZEWIDTH</source>
        <translation>Width:</translation>
    </message>
    <message>
        <source>RES_CED_RESIZEHEIGHT</source>
        <translation>Height:</translation>
    </message>
    <message>
        <source>RES_CED_AUTOFIT</source>
        <translation>Autofit</translation>
    </message>
    <message>
        <source>RES_CED_LAYOUT</source>
        <translation>Layout:</translation>
    </message>
    <message>
        <source>RES_CED_LAYLEFT</source>
        <translation>Left</translation>
    </message>
    <message>
        <source>RES_CED_LAYHCENTRE</source>
        <translation>Centre</translation>
    </message>
    <message>
        <source>RES_CED_LAYRIGHT</source>
        <translation>Right</translation>
    </message>
    <message>
        <source>RES_CED_LAYTOP</source>
        <translation>Top</translation>
    </message>
    <message>
        <source>RES_CED_LAYVCENTRE</source>
        <translation>Centre</translation>
    </message>
    <message>
        <source>RES_CED_LAYBOTTOM</source>
        <translation>Bottom</translation>
    </message>
    <message>
        <source>RES_CED_INDENT</source>
        <translation>Indent:</translation>
    </message>
    <message>
        <source>RES_CED_STYLEFONTMENU</source>
        <translation>Style/Font</translation>
    </message>
    <message>
        <source>RES_CED_FORMATLAYOUTMENU</source>
        <translation>Format/Layout</translation>
    </message>
    <message>
        <source>RES_CED_RESIZEMENU</source>
        <translation>Resize</translation>
    </message>
    <message>
        <source>RES_CED_INSERTDELETEMENU</source>
        <translation>Insert/Delete</translation>
    </message>
    <message>
        <source>RES_CED_HYPERLINKMENU</source>
        <translation>Hyperlink</translation>
    </message>
    <message>
        <source>RES_CED_HYPERLINKURL</source>
        <translation>Hyperlink URL:</translation>
    </message>
    <message>
        <source>RES_CED_BULLETNUMBERMENU</source>
        <translation>Bullets/Numbering</translation>
    </message>
    <message>
        <source>RES_CED_RENUMBER</source>
        <translation>Restart numbering</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTART</source>
        <translation>Start at:</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPE</source>
        <translation>List type:</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPENONE</source>
        <translation>None</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPEBULLET</source>
        <translation>Bullet</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPENUMBER</source>
        <translation>Numbered</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLE</source>
        <translation>Style:</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLEAUTO</source>
        <translation>Auto</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLEDASH</source>
        <translation>Dash</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLEDOT</source>
        <translation>Dot</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLESQUARE</source>
        <translation>Square</translation>
    </message>
    <message>
        <source>RES_CED_NOCOLOUR</source>
        <translation>(None)</translation>
    </message>
    <message>
        <source>RES_CED_COLOURPICKER</source>
        <translation>Colour</translation>
    </message>
    <message>
        <source>RES_CED_SORTCELLS</source>
        <translation>Sort cells</translation>
    </message>
    <message>
        <source>RES_CED_CASESENSITIVE</source>
        <translation>Case Sensitive</translation>
    </message>
    <message>
        <source>RES_CED_SORTASCENDING</source>
        <translation>Ascending</translation>
    </message>
    <message>
        <source>RES_CED_SORTBYCOL</source>
        <translation>Sort by column</translation>
    </message>
    <message>
        <source>RES_CED_SORTBYROW</source>
        <translation>Sort by row</translation>
    </message>
    <message>
        <source>RES_CED_SORTBY_FIRST</source>
        <translation>First sort by</translation>
    </message>
    <message>
        <source>RES_CED_SORTBY_SECOND</source>
        <translation>Then sort by</translation>
    </message>
    <message>
        <source>RES_CED_SORTBY_LAST</source>
        <translation>Finally sort by</translation>
    </message>
    <message>
        <source>RES_CED_SORTNEXT</source>
        <translation>First corner selected, now select second corner for sort range</translation>
    </message>
    <message>
        <source>RES_CED_SORTMENU</source>
        <translation>Sort</translation>
    </message>
</context>
<context>
    <name>FunctionNames</name>
    <message>
        <source>RES_FUNC_NOW</source>
        <translation>NOW</translation>
    </message>
    <message>
        <source>RES_FUNC_FV</source>
        <translation>FV</translation>
    </message>
    <message>
        <source>RES_FUNC_IRR</source>
        <translation>IRR</translation>
    </message>
    <message>
        <source>RES_FUNC_NPER</source>
        <translation>NPER</translation>
    </message>
    <message>
        <source>RES_FUNC_NPV</source>
        <translation>NPV</translation>
    </message>
    <message>
        <source>RES_FUNC_PMT</source>
        <translation>PMT</translation>
    </message>
    <message>
        <source>RES_FUNC_PV</source>
        <translation>PV</translation>
    </message>
    <message>
        <source>RES_FUNC_RATE</source>
        <translation>RATE</translation>
    </message>
    <message>
        <source>RES_FUNC_AND</source>
        <translation>AND</translation>
    </message>
    <message>
        <source>RES_FUNC_FALSE</source>
        <translation>FALSE</translation>
    </message>
    <message>
        <source>RES_FUNC_IF</source>
        <translation>IF</translation>
    </message>
    <message>
        <source>RES_FUNC_NOT</source>
        <translation>NOT</translation>
    </message>
    <message>
        <source>RES_FUNC_OR</source>
        <translation>OR</translation>
    </message>
    <message>
        <source>RES_FUNC_TRUE</source>
        <translation>TRUE</translation>
    </message>
    <message>
        <source>RES_FUNC_ABS</source>
        <translation>ABS</translation>
    </message>
    <message>
        <source>RES_FUNC_INT</source>
        <translation>INT</translation>
    </message>
    <message>
        <source>RES_FUNC_LN</source>
        <translation>LN</translation>
    </message>
    <message>
        <source>RES_FUNC_LOG</source>
        <translation>LOG</translation>
    </message>
    <message>
        <source>RES_FUNC_LOG10</source>
        <translation>LOG10</translation>
    </message>
    <message>
        <source>RES_FUNC_MOD</source>
        <translation>MOD</translation>
    </message>
    <message>
        <source>RES_FUNC_POWER</source>
        <translation>POWER</translation>
    </message>
    <message>
        <source>RES_FUNC_PRODUCT</source>
        <translation>PRODUCT</translation>
    </message>
    <message>
        <source>RES_FUNC_ROUND</source>
        <translation>ROUND</translation>
    </message>
    <message>
        <source>RES_FUNC_SQRT</source>
        <translation>SQRT</translation>
    </message>
    <message>
        <source>RES_FUNC_SUM</source>
        <translation>SUM</translation>
    </message>
    <message>
        <source>RES_FUNC_SUMIF</source>
        <translation>SUMIF</translation>
    </message>
    <message>
        <source>RES_FUNC_TRUNC</source>
        <translation>TRUNC</translation>
    </message>
    <message>
        <source>RES_FUNC_AVERAGE</source>
        <translation>AVERAGE</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNTIF</source>
        <translation>COUNTIF</translation>
    </message>
    <message>
        <source>RES_FUNC_MAX</source>
        <translation>MAX</translation>
    </message>
    <message>
        <source>RES_FUNC_MIN</source>
        <translation>MIN</translation>
    </message>
    <message>
        <source>RES_FUNC_DATE</source>
        <translation>DATE</translation>
    </message>
    <message>
        <source>RES_FUNC_TIME</source>
        <translation>TIME</translation>
    </message>
    <message>
        <source>RES_FUNC_DATEVALUE</source>
        <translation>DATEVALUE</translation>
    </message>
    <message>
        <source>RES_FUNC_TIMEVALUE</source>
        <translation>TIMEVALUE</translation>
    </message>
    <message>
        <source>RES_FUNC_HOUR</source>
        <translation>HOUR</translation>
    </message>
    <message>
        <source>RES_FUNC_MINUTE</source>
        <translation>MINUTE</translation>
    </message>
    <message>
        <source>RES_FUNC_SECOND</source>
        <translation>SECOND</translation>
    </message>
    <message>
        <source>RES_FUNC_DAY</source>
        <translation>DAY</translation>
    </message>
    <message>
        <source>RES_FUNC_MONTH</source>
        <translation>MONTH</translation>
    </message>
    <message>
        <source>RES_FUNC_YEAR</source>
        <translation>YEAR</translation>
    </message>
    <message>
        <source>RES_FUNC_DDB</source>
        <translation>DDB</translation>
    </message>
    <message>
        <source>RES_FUNC_SLN</source>
        <translation>SLN</translation>
    </message>
    <message>
        <source>RES_FUNC_SYD</source>
        <translation>SYD</translation>
    </message>
    <message>
        <source>RES_FUNC_STDEV</source>
        <translation>STDEV</translation>
    </message>
    <message>
        <source>RES_FUNC_STDEVP</source>
        <translation>STDEVP</translation>
    </message>
    <message>
        <source>RES_FUNC_VAR</source>
        <translation>VAR</translation>
    </message>
    <message>
        <source>RES_FUNC_VARP</source>
        <translation>VARP</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNT</source>
        <translation>COUNT</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNTA</source>
        <translation>COUNTA</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNTBLANK</source>
        <translation>COUNTBLANK</translation>
    </message>
</context>
<context>
    <name>DateTime</name>
    <message>
        <source>RES_TIMEDATE_LONGDATEFORMAT</source>
        <translation>dd mmmm yyyy</translation>
    </message>
    <message>
        <source>RES_TIMEDATE_DATEFORMAT</source>
        <translation>dd/mm/yyyy</translation>
    </message>
    <message>
        <source>RES_TIMEDATE_TIMEFORMAT</source>
        <translation>hh:mm</translation>
    </message>
    <message>
        <source>RES_TIMEDATE_DATETIMEFORMAT</source>
        <translation>dd/mm/yyyy hh:mm</translation>
    </message>
    <message>
        <source>RES_DAY_1</source>
        <translation>Sunday</translation>
    </message>
    <message>
        <source>RES_DAY_2</source>
        <translation>Monday</translation>
    </message>
    <message>
        <source>RES_DAY_3</source>
        <translation>Tuesday</translation>
    </message>
    <message>
        <source>RES_DAY_4</source>
        <translation>Wednesday</translation>
    </message>
    <message>
        <source>RES_DAY_5</source>
        <translation>Thursday</translation>
    </message>
    <message>
        <source>RES_DAY_6</source>
        <translation>Friday</translation>
    </message>
    <message>
        <source>RES_DAY_7</source>
        <translation>Saturday</translation>
    </message>
    <message>
        <source>RES_DAYABBR_1</source>
        <translation>Sun</translation>
    </message>
    <message>
        <source>RES_DAYABBR_2</source>
        <translation>Mon</translation>
    </message>
    <message>
        <source>RES_DAYABBR_3</source>
        <translation>Tue</translation>
    </message>
    <message>
        <source>RES_DAYABBR_4</source>
        <translation>Wed</translation>
    </message>
    <message>
        <source>RES_DAYABBR_5</source>
        <translation>Thu</translation>
    </message>
    <message>
        <source>RES_DAYABBR_6</source>
        <translation>Fri</translation>
    </message>
    <message>
        <source>RES_DAYABBR_7</source>
        <translation>Sat</translation>
    </message>
    <message>
        <source>RES_MONTH_1</source>
        <translation>January</translation>
    </message>
    <message>
        <source>RES_MONTH_2</source>
        <translation>February</translation>
    </message>
    <message>
        <source>RES_MONTH_3</source>
        <translation>March</translation>
    </message>
    <message>
        <source>RES_MONTH_4</source>
        <translation>April</translation>
    </message>
    <message>
        <source>RES_MONTH_5</source>
        <translation>May</translation>
    </message>
    <message>
        <source>RES_MONTH_6</source>
        <translation>June</translation>
    </message>
    <message>
        <source>RES_MONTH_7</source>
        <translation>July</translation>
    </message>
    <message>
        <source>RES_MONTH_8</source>
        <translation>August</translation>
    </message>
    <message>
        <source>RES_MONTH_9</source>
        <translation>September</translation>
    </message>
    <message>
        <source>RES_MONTH_10</source>
        <translation>October</translation>
    </message>
    <message>
        <source>RES_MONTH_11</source>
        <translation>November</translation>
    </message>
    <message>
        <source>RES_MONTH_12</source>
        <translation>December</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_1</source>
        <translation>Jan</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_2</source>
        <translation>Feb</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_3</source>
        <translation>Mar</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_4</source>
        <translation>Apr</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_5</source>
        <translation>May</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_6</source>
        <translation>Jun</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_7</source>
        <translation>Jul</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_8</source>
        <translation>Aug</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_9</source>
        <translation>Sep</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_10</source>
        <translation>Oct</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_11</source>
        <translation>Nov</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_12</source>
        <translation>Dec</translation>
    </message>
    <message>
        <source>RES_AMPM_1</source>
        <translation>am</translation>
    </message>
    <message>
        <source>RES_AMPM_2</source>
        <translation>pm</translation>
    </message>
</context>
<context>
    <name>MainWidgetCommon</name>
    <message>
        <source>RES_MENU_FILE</source>
        <translation>File</translation>
    </message>
    <message>
        <source>RES_MENU_OPEN</source>
        <translation>Open</translation>
    </message>
    <message>
        <source>RES_MENU_SAVE</source>
        <translation>Save</translation>
    </message>
    <message>
        <source>RES_MENU_NEW</source>
        <translation>New</translation>
    </message>
    <message>
        <source>RES_MENU_RECENT</source>
        <translation>Recent</translation>
    </message>
    <message>
        <source>RES_MENU_SHUTDOWN</source>
        <translation>Shut Down</translation>
    </message>
    <message>
        <source>RES_MENU_QUIT</source>
        <translation>Quit</translation>
    </message>
    <message>
        <source>RES_MENU_VIEW</source>
        <translation>View</translation>
    </message>
    <message>
        <source>RES_MENU_NEXTPAGE</source>
        <translation>Next Page</translation>
    </message>
    <message>
        <source>RES_MENU_PREVPAGE</source>
        <translation>Prev Page</translation>
    </message>
    <message>
        <source>RES_MENU_ZOOMIN</source>
        <translation>Zoom In</translation>
    </message>
    <message>
        <source>RES_MENU_ZOOMOUT</source>
        <translation>Zoom Out</translation>
    </message>
    <message>
        <source>RES_MENU_FITWIDTH</source>
        <translation>Fit Width</translation>
    </message>
    <message>
        <source>RES_MENU_FITHEIGHT</source>
        <translation>Fit Height</translation>
    </message>
    <message>
        <source>RES_MENU_ROTATEDOC</source>
        <translation>Rotate Document</translation>
    </message>
    <message>
        <source>RES_MENU_REFLOW</source>
        <translation>Cycle Reflow Mode</translation>
    </message>
    <message>
        <source>RES_MENU_THUMBNAIL</source>
        <translation>Thumbnail</translation>
    </message>
    <message>
        <source>RES_MENU_DOCUMENT</source>
        <translation>Document</translation>
    </message>
    <message>
        <source>RES_MENU_GOTOPAGE</source>
        <translation>Go To Page</translation>
    </message>
    <message>
        <source>RES_MENU_GOTOELEMENT</source>
        <translation>Go To Element</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH</source>
        <translation>Search</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_BACK</source>
        <translation>Search Backward</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_FORWARD</source>
        <translation>Search Forward</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_SNAP</source>
        <translation>Search Snap To Result</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_CANCEL</source>
        <translation>Cancel Search</translation>
    </message>
    <message>
        <source>RES_MENU_PAGE</source>
        <translation>Page Edit</translation>
    </message>
    <message>
        <source>RES_MENU_PAGEDELETE</source>
        <translation>Delete</translation>
    </message>
    <message>
        <source>RES_MENU_PAGEMOVEFORWARD</source>
        <translation>Move Forward</translation>
    </message>
    <message>
        <source>RES_MENU_PAGEMOVEBACKWARD</source>
        <translation>Move Backward</translation>
    </message>
    <message>
        <source>RES_MENU_PREFERENCES</source>
        <translation>Preferences</translation>
    </message>
    <message>
        <source>RES_MENU_HELP</source>
        <translation>Help</translation>
    </message>
    <message>
        <source>RES_MENU_ABOUT</source>
        <translation>About</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_ADD</source>
        <translation>Add Annotation</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_VIEW</source>
        <translation>View/Edit Annotation</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_DELETE</source>
        <translation>Delete Annotation</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_SAVE</source>
        <translation>Save Annotations</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_SHOW</source>
        <translation>Show Annotations</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_HIDE</source>
        <translation>Hide Annotations</translation>
    </message>
    <message>
        <source>RES_TITLE_GOTOPAGE</source>
        <translation>Go To Page</translation>
    </message>
    <message>
        <source>RES_HINT_GOTOPAGE</source>
        <translation>Page number:</translation>
    </message>
    <message>
        <source>RES_TITLE_GOTOELEMENT</source>
        <translation>Go To Element</translation>
    </message>
    <message>
        <source>RES_HINT_GOTOELEMENT</source>
        <translation>Element ID, eg "F5":</translation>
    </message>
    <message>
        <source>RES_TITLE_SEARCH</source>
        <translation>Search</translation>
    </message>
    <message>
        <source>RES_HINT_SEARCH</source>
        <translation>Search string:</translation>
    </message>
    <message>
        <source>RES_TITLE_PASSWORD</source>
        <translation>Enter password</translation>
    </message>
    <message>
        <source>RES_HINT_PASSWORD</source>
        <translation>Password:</translation>
    </message>
    <message>
        <source>RES_OK</source>
        <translation>OK</translation>
    </message>
    <message>
        <source>RES_OPEN</source>
        <translation>Open</translation>
    </message>
    <message>
        <source>RES_YES</source>
        <translation>Yes</translation>
    </message>
    <message>
        <source>RES_NO</source>
        <translation>No</translation>
    </message>
    <message>
        <source>RES_CANCEL</source>
        <translation>Cancel</translation>
    </message>
    <message>
        <source>RES_FULLSCREEN</source>
        <translation>Fullscreen</translation>
    </message>
    <message>
        <source>RES_MEMORY_HEAP_KB</source>
        <translation>8192</translation>
    </message>
</context>
<context>
    <name>PrefDialog</name>
    <message>
        <source>RES_PREF_CAPTION</source>
        <translation>Preferences</translation>
    </message>
    <message>
        <source>RES_PREF_SINGLEPAGE</source>
        <translation>Page by page loading</translation>
    </message>
    <message>
        <source>RES_PREF_CHARENCODING</source>
        <translation>Character Set</translation>
    </message>
    <message>
        <source>RES_PREF_DEFENCODING</source>
        <translation>Default</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO88591</source>
        <translation>Western (ISO 8859-1)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_BIG5</source>
        <translation>Traditional Chinese (Big 5)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_GBK</source>
        <translation>Simplified Chinese (GBK)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_SHIFTJIS</source>
        <translation>Japanese (Shift JIS)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO2022JP</source>
        <translation>Japanese (ISO 2022-JP)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_EUCJP</source>
        <translation>Japanese (EUC-JP)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_WINDOWS949</source>
        <translation>Korean (Windows CP 949)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_UTF8</source>
        <translation>Universal (UTF-8)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_WINDOWS1251</source>
        <translation>Windows (Windows CP 1251)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_KOI8</source>
        <translation>Cyrillic (KOI-8)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_WINDOWS866</source>
        <translation>DOS (Windows CP 866)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO88595</source>
        <translation>Cyrillic (ISO 8859-5)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO88597</source>
        <translation>Greek (ISO 8859-7)</translation>
    </message>
    <message>
        <source>RES_PREF_AUTOENCODING</source>
        <translation>Auto Detect</translation>
    </message>
    <message>
        <source>RES_PREF_BASIC</source>
        <translation>Basic</translation>
    </message>
    <message>
        <source>RES_PREF_OTHER</source>
        <translation>Other</translation>
    </message>
    <message>
        <source>RES_PREF_MORE_PREFERENCES</source>
        <translation>More preferences...</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_PREFERENCES</source>
        <translation>OEM Preferences</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_NAME</source>
        <translation>Name</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_VALUE</source>
        <translation>Value</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_RESTART_WARNING</source>
        <translation>The application needs to be restarted before OEM preference changes can take effect.  Restart now?</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_PREF_FONT_COULD_NOT_BE_REGISTERED</source>
        <translation>Error: A font enabled in fileviewer.cfg could not be registered. Please check which languages are defined in the project make file.</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_PREF_FILE_NOT_FOUND</source>
        <translation>The fileviewer.cfg preferences file cannot be found in the current working directory. Preferences may not function correctly.</translation>
    </message>
</context>
<context>
    <name>HelpDialog</name>
    <message>
        <source>RES_HELP_CAPTION</source>
        <translation>Picsel Viewer Help</translation>
    </message>
    <message>
        <source>RES_HELP_UNKNOWN</source>
        <translation>Unknown</translation>
    </message>
</context>
<context>
    <name>AboutDialog</name>
    <message>
        <source>RES_ABOUT_CAPTION</source>
        <translation>About Picsel Viewer</translation>
    </message>
    <message>
        <source>RES_ABOUT_UNKNOWN</source>
        <translation>Unknown</translation>
    </message>
    <message>
        <source>RES_ABOUTWOMARKUP_PART0</source>
        <translation>Picsel Viewer</translation>
    </message>
    <message>
        <source>RES_ABOUTWOMARKUP_PART1</source>
        <translation>(Issue </translation>
    </message>
    <message>
        <source>RES_ABOUTWOMARKUP_PART2</source>
        <translation>)</translation>
    </message>
    <message>
        <source>RES_ABOUT_PART0</source>
        <translation><![CDATA[<qt><h3>Picsel Viewer&trade;.</h3><em>Version ]]></translation>
    </message>
    <message>
        <source>RES_ABOUT_PART1</source>
        <translation> (Issue </translation>
    </message>
    <message>
        <source>RES_ABOUT_PART2</source>
        <translation><![CDATA[)</em><p><font size=2><p><p>Powered by Picsel ePAGE&reg; technology.<br>Copyright &copy; Picsel 2000-2008.  All rights reserved.<p><hr>This computer program, user interface and design are protected by international, US and European copyright laws. US and international Patents applied for. Picsel, Picsel Viewer, ePAGE and the Picsel cube logo are trademarks or registered trademarks of Picsel Technologies Ltd.<p><p>This version of the Picsel Viewer has been licensed only for use by ]]></translation>
    </message>
    <message>
        <source>RES_ABOUT_PART3</source>
        <translation><![CDATA[.<p><hr><h4>Acknowledgements</h4><p>This software is based in part on the work of the independent JPEG group. <p>String library &copy; 1999-2000 Ralf S. Engelschall rse@engelschall.com.<p>This product includes software developed by the Apache Group for use in the Apache HTTP server project (http://www.apache.org/).<p>Parts of this software are derived from the RSA Data Security, Inc. MD5 Message-Digest Algorithm.<p>LZW decoder for GIF, &copy; 1987, by Steven A. Bennett.<p>'C' functions Copyright &copy; 1988, 1993 The Regents of the University of California.</qt>]]></translation>
    </message>
</context>
<context>
    <name>DirDialog</name>
    <message>
        <source>RES_DIR_CAPTION</source>
        <translation>Directory</translation>
    </message>
    <message>
        <source>RES_DIR_UNKNOWN</source>
        <translation>Unknown</translation>
    </message>
</context>
<context>
    <name>Core</name>
    <message>
        <source>RES_ALERT_DOCTRANSLATIONFAILED</source>
        <translation>The application cannot display this file</translation>
    </message>
    <message>
        <source>RES_ALERT_INTERNALERROR</source>
        <translation>Internal Error</translation>
    </message>
    <message>
        <source>RES_ALERT_OUTOFMEMORY</source>
        <translation>Out of Memory</translation>
    </message>
    <message>
        <source>RES_ALERT_UNKNOWNERROR</source>
        <translation>Unknown Error occurred</translation>
    </message>
    <message>
        <source>RES_ALERT_DOCSAVEDSUCCESSFULLY</source>
        <translation>The document was saved successfully</translation>
    </message>
    <message>
        <source>RES_ALERT_DOCSAVEERROR</source>
        <translation>An error has occurred during saving</translation>
    </message>
    <message>
        <source>RES_ALERT_SEARCHERROR</source>
        <translation>Search error</translation>
    </message>
    <message>
        <source>RES_ALERT_SEARCHFAILED</source>
        <translation>Search failed - not found</translation>
    </message>
    <message>
        <source>RES_ALERT_SEARCHWRAPPED</source>
        <translation>Search wrapped - continue?</translation>
    </message>
    <message>
        <source>RES_ALERT_GOTOFAILED</source>
        <translation>Go to failed - element not found</translation>
    </message>
    <message>
        <source>RES_ALERT_GOTOERROR</source>
        <translation>Go to failed</translation>
    </message>
    <message>
        <source>RES_ALERT_NOTHINGSELECTED</source>
        <translation>Did not select anything</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTOEDIT</source>
        <translation>Failed to edit this selection</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTODELETE</source>
        <translation>Failed to delete</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTOINSERT</source>
        <translation>Failed to insert</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTOUPDATE</source>
        <translation>Failed to update document</translation>
    </message>
    <message>
        <source>RES_ALERT_COULDNOTINSERTHERE</source>
        <translation>Could not insert here</translation>
    </message>
    <message>
        <source>RES_ALERT_COULDNOTINSERTMAX</source>
        <translation>Could not insert - document at maximum size</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTODESELECT</source>
        <translation>Failed to deselect.  Try again or reload your document</translation>
    </message>
    <message>
        <source>RES_ALERT_INVALIDFONTSIZE</source>
        <translation>Font size invalid. Valid sizes are 2-144 pt</translation>
    </message>
    <message>
        <source>RES_ALERT_INVALIDFORMATSTRING</source>
        <translation>Invalid format string specified</translation>
    </message>
    <message>
        <source>RES_ALERT_DOCNOTEDITABLE</source>
        <translation>This document is not editable</translation>
    </message>
    <message>
        <source>RES_ALERT_ERRORINFORMULA</source>
        <translation>An Excel formula has returned an error result</translation>
    </message>
    <message>
        <source>RES_ALERT_FORMULAUNSUPPORTED</source>
        <translation>Failed to parse formula</translation>
    </message>
    <message>
        <source>RES_ALERT_CIRCULARDEPENDENCY</source>
        <translation>Found circular dependency in formula</translation>
    </message>
    <message>
        <source>RES_ALERT_ARRAYNOTSUPPORTED</source>
        <translation>Updating array or table formulae is not supported</translation>
    </message>
    <message>
        <source>RES_ALERT_SORTFAILED</source>
        <translation>Sorting has failed</translation>
    </message>
    <message>
        <source>RES_ALERT_INVALIDGOTO</source>
        <translation>The value specified does not appear to be a valid cell location</translation>
    </message>
    <message>
        <source>RES_ALERT_FORMULASUNSUPPORTED</source>
        <translation>The document contains formulas not supported by Picsel.
It is not possible to edit this document.</translation>
    </message>
    <message>
        <source>RES_ALERT_IMAGESUBSAMPLED</source>
        <translation>Images within the document have been subsampled to conserve memory</translation>
    </message>
    <message>
        <source>RES_ALERT_TABLERESTRICTION</source>
        <translation>Row/column insertion/deletion is not allowed within a table or pivot table</translation>
    </message>
    <message>
        <source>RES_ALERT_ANNOTATION_SAVED</source>
        <translation>Annotations have been saved</translation>
    </message>
    <message>
        <source>RES_CONFIRM_ANNOTATION_LOAD</source>
        <translation>Annotation file found.  Load it?</translation>
    </message>
    <message>
        <source>RES_CONFIRM_OPENNEW</source>
        <translation>You have edited this document.
Do you really want to open this new document, and lose your edits?</translation>
    </message>
    <message>
        <source>RES_CONFIRM_CONFIRMQUIT</source>
        <translation>You have edited this document.
Do you really want to quit, and lose your edits?</translation>
    </message>
    <message>
        <source>RES_CONFIRM_CONTENTLOSS</source>
        <translation>The original document is not present, if you save the document now, pictures will be lost.
Do you wish to continue?</translation>
    </message>
</context>
</TS>
