<!-- auto-generated by ./tsv2ts.pl from picseledit.csv on Thu Sep 24 14:15:51 2009 -->

<!-- Copyright (C) Picsel, 2007. All Rights Reserved. -->

<!-- @author Picsel Technologies Ltd -->

<!-- $Id: picseledit-fr-ca.ts,v 1.19 2009/09/28 10:46:59 neilk Exp $ -->

<!DOCTYPE TS><TS>
<context>
    <name>ContentsEditDialog</name>
    <message>
        <source>RES_CED_Brazil</source>
        <translation>Brésil</translation>
    </message>
    <message>
        <source>RES_CED_Uruguay</source>
        <translation>Uruguay</translation>
    </message>
    <message>
        <source>RES_CED_Argentina</source>
        <translation>Argentine</translation>
    </message>
    <message>
        <source>RES_CED_Colombia</source>
        <translation>Colombie</translation>
    </message>
    <message>
        <source>RES_CED_Guatemala</source>
        <translation>Guatemala</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia</source>
        <translation>Bolivie</translation>
    </message>
    <message>
        <source>RES_CED_Chile</source>
        <translation>Chili</translation>
    </message>
    <message>
        <source>RES_CED_DominicanRepublic</source>
        <translation>République dominicaine</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador</source>
        <translation>Équateur</translation>
    </message>
    <message>
        <source>RES_CED_Mexico</source>
        <translation>Mexique</translation>
    </message>
    <message>
        <source>RES_CED_Peru</source>
        <translation>Pérou</translation>
    </message>
    <message>
        <source>RES_CED_Paraguay</source>
        <translation>Paraguay</translation>
    </message>
    <message>
        <source>RES_CED_ElSalvador</source>
        <translation>Salvador</translation>
    </message>
    <message>
        <source>RES_CED_TrinidadTobago</source>
        <translation>Trinidad</translation>
    </message>
    <message>
        <source>RES_CED_Honduras</source>
        <translation>Honduras</translation>
    </message>
    <message>
        <source>RES_CED_Nicaragua</source>
        <translation>Nicaragua</translation>
    </message>
    <message>
        <source>RES_CED_Venezuela</source>
        <translation>Vénézuela</translation>
    </message>
    <message>
        <source>RES_CED_Panama</source>
        <translation>Panama</translation>
    </message>
    <message>
        <source>RES_CED_CostaRica</source>
        <translation>Costa Rica</translation>
    </message>
    <message>
        <source>RES_CED_Jamaica</source>
        <translation>Jamaïque</translation>
    </message>
    <message>
        <source>RES_CED_FrenchCanada</source>
        <translation>Français Canada</translation>
    </message>
    <message>
        <source>RES_CED_UnitedKingdom</source>
        <translation>Royaume-Uni</translation>
    </message>
    <message>
        <source>RES_CED_UnitedStates</source>
        <translation>États-Unis</translation>
    </message>
    <message>
        <source>RES_CED_ISO</source>
        <translation>ISO</translation>
    </message>
    <message>
        <source>RES_CED_Local</source>
        <translation>Local</translation>
    </message>
    <message>
        <source>RES_CED_HongKong</source>
        <translation>Hong Kong</translation>
    </message>
    <message>
        <source>RES_CED_Taiwan</source>
        <translation>Taiwan</translation>
    </message>
    <message>
        <source>RES_CED_Indonesia</source>
        <translation>Indonesia</translation>
    </message>
    <message>
        <source>RES_CED_Malaysia</source>
        <translation>Malaysia</translation>
    </message>
    <message>
        <source>RES_CED_Philippines</source>
        <translation>Philippines</translation>
    </message>
    <message>
        <source>RES_CED_Thailand</source>
        <translation>Thailand</translation>
    </message>
    <message>
        <source>RES_CED_Vietnam</source>
        <translation>Vietnam</translation>
    </message>
    <message>
        <source>RES_CED_Brazil_Real</source>
        <translation>Brésil : Real</translation>
    </message>
    <message>
        <source>RES_CED_Uruguay_Peso</source>
        <translation>Uruguay : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Argentina_Peso</source>
        <translation>Argentine : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Colombia_Peso</source>
        <translation>Colombie : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Guatemala_Quetzal</source>
        <translation>Guatemala : Quetzal</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia_Boliviano_Quechua</source>
        <translation>Bolivie : Boliviano (Quechua)</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia_Boliviano_Spanish</source>
        <translation>Bolivie : Boliviano (Espagnol)</translation>
    </message>
    <message>
        <source>RES_CED_Chile_Peso</source>
        <translation>Chili : Peso</translation>
    </message>
    <message>
        <source>RES_CED_DominicanRepublic_Peso</source>
        <translation>République dominicaine : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador_Sucre_Quechua</source>
        <translation>Équateur : Sucre (Quechua)</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador_Sucre_Spanish</source>
        <translation>Équateur : Sucre (Espagnol)</translation>
    </message>
    <message>
        <source>RES_CED_Mexico_Peso</source>
        <translation>Mexique : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Peru_NuevoSol_Quechua</source>
        <translation>Pérou : Nuevo Sol (Quechua)</translation>
    </message>
    <message>
        <source>RES_CED_Peru_NuevoSol_Spanish</source>
        <translation>Pérou : Nuevo Sol (Espagnol)</translation>
    </message>
    <message>
        <source>RES_CED_Paraguay_Guarani</source>
        <translation>Paraguay : Guarani</translation>
    </message>
    <message>
        <source>RES_CED_ElSalvador_Colon</source>
        <translation>Salvador : Colon</translation>
    </message>
    <message>
        <source>RES_CED_TrinidadTobago_Dollar</source>
        <translation>Trinidad : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Honduras_Lempira</source>
        <translation>Honduras : Lempira</translation>
    </message>
    <message>
        <source>RES_CED_Nicaragua_Cordoba</source>
        <translation>Nicaragua : Cordoba</translation>
    </message>
    <message>
        <source>RES_CED_Venezuela_Bolivar</source>
        <translation>Vénézuela : Bolivar</translation>
    </message>
    <message>
        <source>RES_CED_Panama_Balboa</source>
        <translation>Panama : Balboa</translation>
    </message>
    <message>
        <source>RES_CED_CostaRica_Colon</source>
        <translation>Costa Rica : Colon</translation>
    </message>
    <message>
        <source>RES_CED_Jamaica_Dollar</source>
        <translation>Jamaïque : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_FrenchCanada_Dollar</source>
        <translation>Français Canada : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Sterling</source>
        <translation>Sterling</translation>
    </message>
    <message>
        <source>RES_CED_UnitedKingdom_Pound</source>
        <translation>Royaume-Uni : Pound</translation>
    </message>
    <message>
        <source>RES_CED_UnitedStates_Dollar</source>
        <translation>États-Unis : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Euro</source>
        <translation>Euro</translation>
    </message>
    <message>
        <source>RES_CED_Euro_Alt</source>
        <translation>Euro (Alt)</translation>
    </message>
    <message>
        <source>RES_CED_HongKong_Dollar</source>
        <translation>Hong Kong : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Taiwan_Dollar</source>
        <translation>Taiwan : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Indonesia_Rupiah</source>
        <translation>Indonesia : Rupiah</translation>
    </message>
    <message>
        <source>RES_CED_Malaysia_Ringgit</source>
        <translation>Malaysia : Ringgit</translation>
    </message>
    <message>
        <source>RES_CED_Philippines_Peso</source>
        <translation>Philippines : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Thailand_Baht</source>
        <translation>Thailand : Baht</translation>
    </message>
    <message>
        <source>RES_CED_Vietnam_Dong</source>
        <translation>Vietnam : Dong</translation>
    </message>
    <message>
        <source>RES_CED_Brazil_Real_Name</source>
        <translation>Brésil : Real (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Uruguay_Peso_Name</source>
        <translation>Uruguay : Peso (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Argentina_Peso_Name</source>
        <translation>Argentine : Peso (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Colombia_Peso_Name</source>
        <translation>Colombie : Peso (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Guatemala_Quetzal_Name</source>
        <translation>Guatemala : Quetzal (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia_Boliviano_Name</source>
        <translation>Bolivie : Boliviano (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Chile_Peso_Name</source>
        <translation>Chili : Peso (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_DominicanRepublic_Peso_Name</source>
        <translation>République dominicaine : Peso (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador_Sucre_Name</source>
        <translation>Équateur : Sucre (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Mexico_Peso_Name</source>
        <translation>Mexique : Peso (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Peru_NuevoSol_Name</source>
        <translation>Pérou : Nuevo Sol (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Paraguay_Guarani_Name</source>
        <translation>Paraguay : Guarani (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_ElSalvador_Colon_Name</source>
        <translation>Salvador : Colon (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_TrinidadTobago_Dollar_Name</source>
        <translation>Trinidad : Dollar (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Honduras_Lempira_Name</source>
        <translation>Honduras : Lempira (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Nicaragua_Cordoba_Name</source>
        <translation>Nicaragua : Cordoba (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Venezuela_Bolivar_Name</source>
        <translation>Vénézuela : Bolivar (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Panama_Balboa_Name</source>
        <translation>Panama : Balboa (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_CostaRica_Colon_Name</source>
        <translation>Costa Rica : Colon (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Haiti_Gourde_Name</source>
        <translation>Haïti : Gourde (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Jamaica_Dollar_Name</source>
        <translation>Jamaïque : Dollar (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_UnitedKingdom_Pound_Name</source>
        <translation>Royaume-Uni : Pound (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_UnitedStates_Dollar_Name</source>
        <translation>États-Unis : Dollar (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_Euro_Name</source>
        <translation>Euro (Nom)</translation>
    </message>
    <message>
        <source>RES_CED_HongKong_Dollar_Name</source>
        <translation>Hong Kong : Dollar (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Taiwan_Dollar_Name</source>
        <translation>Taiwan : Dollar (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Indonesia_Rupiah_Name</source>
        <translation>Indonesia : Rupiah (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Malaysia_Ringgit_Name</source>
        <translation>Malaysia : Ringgit (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Philippines_Peso_Name</source>
        <translation>Philippines : Peso (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Thailand_Baht_Name</source>
        <translation>Thailand : Baht (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Vietnam_Dong_Name</source>
        <translation>Vietnam : Dong (Name)</translation>
    </message>
    <message>
        <source>RES_CED_NEG1</source>
        <translation>Utiliser signe -ve</translation>
    </message>
    <message>
        <source>RES_CED_NEG2</source>
        <translation>Pas de signe -ve, Rouge</translation>
    </message>
    <message>
        <source>RES_CED_NEG3</source>
        <translation>Utiliser signe -ve, décalage</translation>
    </message>
    <message>
        <source>RES_CED_NEG4</source>
        <translation>Utiliser signe -ve, Rouge, décalage</translation>
    </message>
    <message>
        <source>RES_CED_DP0</source>
        <translation>Pas de décimale</translation>
    </message>
    <message>
        <source>RES_CED_DP1</source>
        <translation>Une décimale</translation>
    </message>
    <message>
        <source>RES_CED_DP2</source>
        <translation>Deux décimales</translation>
    </message>
    <message>
        <source>RES_CED_DP3</source>
        <translation>Trois décimales</translation>
    </message>
    <message>
        <source>RES_CED_DP10</source>
        <translation>Dix décimales</translation>
    </message>
    <message>
        <source>RES_CED_NOCOMMAS</source>
        <translation>Pas de virgule</translation>
    </message>
    <message>
        <source>RES_CED_COMMAS</source>
        <translation>Virgule</translation>
    </message>
    <message>
        <source>RES_CED_LONGDATEFORMAT</source>
        <translation>Date formelle</translation>
    </message>
    <message>
        <source>RES_CED_DATEFORMAT</source>
        <translation>Date</translation>
    </message>
    <message>
        <source>RES_CED_TIMEFORMAT</source>
        <translation>Heure</translation>
    </message>
    <message>
        <source>RES_CED_DATETIMEFORMAT</source>
        <translation>Date et heure</translation>
    </message>
    <message>
        <source>RES_CED_FRAC1</source>
        <translation>D'un chiffre</translation>
    </message>
    <message>
        <source>RES_CED_FRAC2</source>
        <translation>De deux chiffres</translation>
    </message>
    <message>
        <source>RES_CED_FRAC3</source>
        <translation>De trois chiffres</translation>
    </message>
    <message>
        <source>RES_CED_FRAC4</source>
        <translation>Demis</translation>
    </message>
    <message>
        <source>RES_CED_FRAC5</source>
        <translation>Quarts</translation>
    </message>
    <message>
        <source>RES_CED_FRAC6</source>
        <translation>Huitièmes</translation>
    </message>
    <message>
        <source>RES_CED_FRAC7</source>
        <translation>Seizièmes</translation>
    </message>
    <message>
        <source>RES_CED_FRAC8</source>
        <translation>Dixièmes</translation>
    </message>
    <message>
        <source>RES_CED_FRAC9</source>
        <translation>Centièmes</translation>
    </message>
    <message>
        <source>RES_CED_GENERAL</source>
        <translation>Général</translation>
    </message>
    <message>
        <source>RES_CED_NUMBER</source>
        <translation>Nombre</translation>
    </message>
    <message>
        <source>RES_CED_CURRENCY</source>
        <translation>Monétaire</translation>
    </message>
    <message>
        <source>RES_CED_ACCOUNTING</source>
        <translation>Comptabilité</translation>
    </message>
    <message>
        <source>RES_CED_DATE</source>
        <translation>Date</translation>
    </message>
    <message>
        <source>RES_CED_TIME</source>
        <translation>Heure</translation>
    </message>
    <message>
        <source>RES_CED_PERCENTAGE</source>
        <translation>Pourcentage</translation>
    </message>
    <message>
        <source>RES_CED_FRACTION</source>
        <translation>Fraction</translation>
    </message>
    <message>
        <source>RES_CED_SCIENTIFIC</source>
        <translation>Scientifique</translation>
    </message>
    <message>
        <source>RES_CED_TEXT</source>
        <translation>Texte</translation>
    </message>
    <message>
        <source>RES_CED_CUSTOM</source>
        <translation>Personnalisée</translation>
    </message>
    <message>
        <source>RES_CED_NOACTION</source>
        <translation>No action</translation>
    </message>
    <message>
        <source>RES_CED_INSERTROWBEFORE</source>
        <translation>Insérer la ligne avant</translation>
    </message>
    <message>
        <source>RES_CED_INSERTCOLUMNBEFORE</source>
        <translation>Insérer la colonne avant</translation>
    </message>
    <message>
        <source>RES_CED_INSERTTABLE</source>
        <translation>Insert Table</translation>
    </message>
    <message>
        <source>RES_CED_DELETECURRENTROW</source>
        <translation>Effacer la ligne actuelle</translation>
    </message>
    <message>
        <source>RES_CED_DELETECURRENTCOLUMN</source>
        <translation>Effacer la colonne en cours</translation>
    </message>
    <message>
        <source>RES_CED_DELETETABLE</source>
        <translation>Supprimer tableau</translation>
    </message>
    <message>
        <source>RES_CED_TITLE</source>
        <translation>Édition </translation>
    </message>
    <message>
        <source>RES_CED_REPLACE</source>
        <translation>Replace</translation>
    </message>
    <message>
        <source>RES_CED_INSERTABOVE</source>
        <translation>Insert Above</translation>
    </message>
    <message>
        <source>RES_CED_INSERTBELOW</source>
        <translation>Insert Below</translation>
    </message>
    <message>
        <source>RES_CED_STYLE</source>
        <translation>Style:</translation>
    </message>
    <message>
        <source>RES_CED_SIZE</source>
        <translation>Taille:</translation>
    </message>
    <message>
        <source>RES_CED_COLOUR</source>
        <translation>Couleur:</translation>
    </message>
    <message>
        <source>RES_CED_HIGHLIGHT</source>
        <translation>Surlignage:</translation>
    </message>
    <message>
        <source>RES_CED_FONT</source>
        <translation>Police:</translation>
    </message>
    <message>
        <source>RES_CED_FORMAT</source>
        <translation>Format:</translation>
    </message>
    <message>
        <source>RES_CED_RESIZEWIDTH</source>
        <translation>Largeur:</translation>
    </message>
    <message>
        <source>RES_CED_RESIZEHEIGHT</source>
        <translation>Hauteur:</translation>
    </message>
    <message>
        <source>RES_CED_AUTOFIT</source>
        <translation>Ajustement automatique</translation>
    </message>
    <message>
        <source>RES_CED_LAYOUT</source>
        <translation>Mise en forme:</translation>
    </message>
    <message>
        <source>RES_CED_LAYLEFT</source>
        <translation>Gauche</translation>
    </message>
    <message>
        <source>RES_CED_LAYHCENTRE</source>
        <translation>Centré</translation>
    </message>
    <message>
        <source>RES_CED_LAYRIGHT</source>
        <translation>Droite</translation>
    </message>
    <message>
        <source>RES_CED_LAYTOP</source>
        <translation>Haut</translation>
    </message>
    <message>
        <source>RES_CED_LAYVCENTRE</source>
        <translation>Centré</translation>
    </message>
    <message>
        <source>RES_CED_LAYBOTTOM</source>
        <translation>Bas</translation>
    </message>
    <message>
        <source>RES_CED_INDENT</source>
        <translation>Indent:</translation>
    </message>
    <message>
        <source>RES_CED_STYLEFONTMENU</source>
        <translation>Style/Police</translation>
    </message>
    <message>
        <source>RES_CED_FORMATLAYOUTMENU</source>
        <translation>Format/Mise en forme</translation>
    </message>
    <message>
        <source>RES_CED_RESIZEMENU</source>
        <translation>Redimensionner</translation>
    </message>
    <message>
        <source>RES_CED_INSERTDELETEMENU</source>
        <translation>Insérer/Effacer</translation>
    </message>
    <message>
        <source>RES_CED_HYPERLINKMENU</source>
        <translation>Lien hypertexte</translation>
    </message>
    <message>
        <source>RES_CED_HYPERLINKURL</source>
        <translation>Adresse du lien hypertexte:</translation>
    </message>
    <message>
        <source>RES_CED_BULLETNUMBERMENU</source>
        <translation>Puces et numéros</translation>
    </message>
    <message>
        <source>RES_CED_RENUMBER</source>
        <translation>Recommencer la numérotation</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTART</source>
        <translation>Commencer à :</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPE</source>
        <translation>Styles de liste :</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPENONE</source>
        <translation>Aucune liste</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPEBULLET</source>
        <translation>Avec puces</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPENUMBER</source>
        <translation>Numéros</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLE</source>
        <translation>Styles de liste :</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLEAUTO</source>
        <translation>Auto</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLEDASH</source>
        <translation>Tiret</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLEDOT</source>
        <translation>Point</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLESQUARE</source>
        <translation>Carré</translation>
    </message>
    <message>
        <source>RES_CED_NOCOLOUR</source>
        <translation>(Aucune)</translation>
    </message>
    <message>
        <source>RES_CED_COLOURPICKER</source>
        <translation>Couleur</translation>
    </message>
    <message>
        <source>RES_CED_SORTCELLS</source>
        <translation>Sort cells</translation>
    </message>
    <message>
        <source>RES_CED_CASESENSITIVE</source>
        <translation>Case Sensitive</translation>
    </message>
    <message>
        <source>RES_CED_SORTASCENDING</source>
        <translation>Ascending</translation>
    </message>
    <message>
        <source>RES_CED_SORTBYCOL</source>
        <translation>Sort by column</translation>
    </message>
    <message>
        <source>RES_CED_SORTBYROW</source>
        <translation>Sort by row</translation>
    </message>
    <message>
        <source>RES_CED_SORTBY_FIRST</source>
        <translation>First sort by</translation>
    </message>
    <message>
        <source>RES_CED_SORTBY_SECOND</source>
        <translation>Then sort by</translation>
    </message>
    <message>
        <source>RES_CED_SORTBY_LAST</source>
        <translation>Finally sort by</translation>
    </message>
    <message>
        <source>RES_CED_SORTNEXT</source>
        <translation>First corner selected, now select second corner for sort range</translation>
    </message>
    <message>
        <source>RES_CED_SORTMENU</source>
        <translation>Sort</translation>
    </message>
</context>
<context>
    <name>FunctionNames</name>
    <message>
        <source>RES_FUNC_NOW</source>
        <translation>MAINTENANT</translation>
    </message>
    <message>
        <source>RES_FUNC_FV</source>
        <translation>VC</translation>
    </message>
    <message>
        <source>RES_FUNC_IRR</source>
        <translation>TRI</translation>
    </message>
    <message>
        <source>RES_FUNC_NPER</source>
        <translation>NPM</translation>
    </message>
    <message>
        <source>RES_FUNC_NPV</source>
        <translation>VAN</translation>
    </message>
    <message>
        <source>RES_FUNC_PMT</source>
        <translation>VPM</translation>
    </message>
    <message>
        <source>RES_FUNC_PV</source>
        <translation>VA</translation>
    </message>
    <message>
        <source>RES_FUNC_RATE</source>
        <translation>TAUX</translation>
    </message>
    <message>
        <source>RES_FUNC_AND</source>
        <translation>ET</translation>
    </message>
    <message>
        <source>RES_FUNC_FALSE</source>
        <translation>FAUX</translation>
    </message>
    <message>
        <source>RES_FUNC_IF</source>
        <translation>SI</translation>
    </message>
    <message>
        <source>RES_FUNC_NOT</source>
        <translation>NON</translation>
    </message>
    <message>
        <source>RES_FUNC_OR</source>
        <translation>OU</translation>
    </message>
    <message>
        <source>RES_FUNC_TRUE</source>
        <translation>VRAI</translation>
    </message>
    <message>
        <source>RES_FUNC_ABS</source>
        <translation>ABS</translation>
    </message>
    <message>
        <source>RES_FUNC_INT</source>
        <translation>ENT</translation>
    </message>
    <message>
        <source>RES_FUNC_LN</source>
        <translation>LN</translation>
    </message>
    <message>
        <source>RES_FUNC_LOG</source>
        <translation>LOG</translation>
    </message>
    <message>
        <source>RES_FUNC_LOG10</source>
        <translation>LOG10</translation>
    </message>
    <message>
        <source>RES_FUNC_MOD</source>
        <translation>MOD</translation>
    </message>
    <message>
        <source>RES_FUNC_POWER</source>
        <translation>PUISSANCE</translation>
    </message>
    <message>
        <source>RES_FUNC_PRODUCT</source>
        <translation>PRODUIT</translation>
    </message>
    <message>
        <source>RES_FUNC_ROUND</source>
        <translation>ARRONDI</translation>
    </message>
    <message>
        <source>RES_FUNC_SQRT</source>
        <translation>RACINE</translation>
    </message>
    <message>
        <source>RES_FUNC_SUM</source>
        <translation>SOMME</translation>
    </message>
    <message>
        <source>RES_FUNC_SUMIF</source>
        <translation>SOMME.SI</translation>
    </message>
    <message>
        <source>RES_FUNC_TRUNC</source>
        <translation>TRONQUE</translation>
    </message>
    <message>
        <source>RES_FUNC_AVERAGE</source>
        <translation>MOYENNE</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNTIF</source>
        <translation>NB.SI</translation>
    </message>
    <message>
        <source>RES_FUNC_MAX</source>
        <translation>MAX</translation>
    </message>
    <message>
        <source>RES_FUNC_MIN</source>
        <translation>MIN</translation>
    </message>
    <message>
        <source>RES_FUNC_DATE</source>
        <translation>DATE</translation>
    </message>
    <message>
        <source>RES_FUNC_TIME</source>
        <translation>HEURE</translation>
    </message>
    <message>
        <source>RES_FUNC_DATEVALUE</source>
        <translation>DATEVAL</translation>
    </message>
    <message>
        <source>RES_FUNC_TIMEVALUE</source>
        <translation>TEMPSVAL</translation>
    </message>
    <message>
        <source>RES_FUNC_HOUR</source>
        <translation>HEURE</translation>
    </message>
    <message>
        <source>RES_FUNC_MINUTE</source>
        <translation>MINUTE</translation>
    </message>
    <message>
        <source>RES_FUNC_SECOND</source>
        <translation>SECONDE</translation>
    </message>
    <message>
        <source>RES_FUNC_DAY</source>
        <translation>JOUR</translation>
    </message>
    <message>
        <source>RES_FUNC_MONTH</source>
        <translation>MOIS</translation>
    </message>
    <message>
        <source>RES_FUNC_YEAR</source>
        <translation>ANNÉE</translation>
    </message>
    <message>
        <source>RES_FUNC_DDB</source>
        <translation>DDB</translation>
    </message>
    <message>
        <source>RES_FUNC_SLN</source>
        <translation>AMORLIN</translation>
    </message>
    <message>
        <source>RES_FUNC_SYD</source>
        <translation>SYD</translation>
    </message>
    <message>
        <source>RES_FUNC_STDEV</source>
        <translation>ÉCARTYPE</translation>
    </message>
    <message>
        <source>RES_FUNC_STDEVP</source>
        <translation>ÉCARTYPEP</translation>
    </message>
    <message>
        <source>RES_FUNC_VAR</source>
        <translation>VAR</translation>
    </message>
    <message>
        <source>RES_FUNC_VARP</source>
        <translation>VAR.P</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNT</source>
        <translation>NB.SI</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNTA</source>
        <translation>NBVAL</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNTBLANK</source>
        <translation>NB.VIDE</translation>
    </message>
</context>
<context>
    <name>DateTime</name>
    <message>
        <source>RES_TIMEDATE_LONGDATEFORMAT</source>
        <translation>dd/mmmm/yyyy</translation>
    </message>
    <message>
        <source>RES_TIMEDATE_DATEFORMAT</source>
        <translation>dd/mm/yyyy</translation>
    </message>
    <message>
        <source>RES_TIMEDATE_TIMEFORMAT</source>
        <translation>hh:mm</translation>
    </message>
    <message>
        <source>RES_TIMEDATE_DATETIMEFORMAT</source>
        <translation>dd/mm/yyyy hh:mm</translation>
    </message>
    <message>
        <source>RES_DAY_1</source>
        <translation>Dimanche</translation>
    </message>
    <message>
        <source>RES_DAY_2</source>
        <translation>Lundi</translation>
    </message>
    <message>
        <source>RES_DAY_3</source>
        <translation>Mardi</translation>
    </message>
    <message>
        <source>RES_DAY_4</source>
        <translation>Mercredi</translation>
    </message>
    <message>
        <source>RES_DAY_5</source>
        <translation>Jeudi</translation>
    </message>
    <message>
        <source>RES_DAY_6</source>
        <translation>Vendredi</translation>
    </message>
    <message>
        <source>RES_DAY_7</source>
        <translation>Samedi</translation>
    </message>
    <message>
        <source>RES_DAYABBR_1</source>
        <translation>Dimanche</translation>
    </message>
    <message>
        <source>RES_DAYABBR_2</source>
        <translation>Lun</translation>
    </message>
    <message>
        <source>RES_DAYABBR_3</source>
        <translation>Mar</translation>
    </message>
    <message>
        <source>RES_DAYABBR_4</source>
        <translation>Mer</translation>
    </message>
    <message>
        <source>RES_DAYABBR_5</source>
        <translation>Jeu</translation>
    </message>
    <message>
        <source>RES_DAYABBR_6</source>
        <translation>Ven</translation>
    </message>
    <message>
        <source>RES_DAYABBR_7</source>
        <translation>Sam</translation>
    </message>
    <message>
        <source>RES_MONTH_1</source>
        <translation>Janvier</translation>
    </message>
    <message>
        <source>RES_MONTH_2</source>
        <translation>Février</translation>
    </message>
    <message>
        <source>RES_MONTH_3</source>
        <translation>Mars</translation>
    </message>
    <message>
        <source>RES_MONTH_4</source>
        <translation>Avril</translation>
    </message>
    <message>
        <source>RES_MONTH_5</source>
        <translation>Mai</translation>
    </message>
    <message>
        <source>RES_MONTH_6</source>
        <translation>Juin</translation>
    </message>
    <message>
        <source>RES_MONTH_7</source>
        <translation>Juillet</translation>
    </message>
    <message>
        <source>RES_MONTH_8</source>
        <translation>Août</translation>
    </message>
    <message>
        <source>RES_MONTH_9</source>
        <translation>Septembre</translation>
    </message>
    <message>
        <source>RES_MONTH_10</source>
        <translation>Octobre</translation>
    </message>
    <message>
        <source>RES_MONTH_11</source>
        <translation>Novembre</translation>
    </message>
    <message>
        <source>RES_MONTH_12</source>
        <translation>Décembre</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_1</source>
        <translation>Janv</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_2</source>
        <translation>Févr</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_3</source>
        <translation>Mars</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_4</source>
        <translation>Avr</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_5</source>
        <translation>Mai</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_6</source>
        <translation>Juin</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_7</source>
        <translation>Juil</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_8</source>
        <translation>Août</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_9</source>
        <translation>Sept</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_10</source>
        <translation>Oct</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_11</source>
        <translation>Nov</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_12</source>
        <translation>Déc</translation>
    </message>
    <message>
        <source>RES_AMPM_1</source>
        <translation>AM</translation>
    </message>
    <message>
        <source>RES_AMPM_2</source>
        <translation>PM</translation>
    </message>
</context>
<context>
    <name>MainWidgetCommon</name>
    <message>
        <source>RES_MENU_FILE</source>
        <translation>Fichier</translation>
    </message>
    <message>
        <source>RES_MENU_OPEN</source>
        <translation>Ouvrir</translation>
    </message>
    <message>
        <source>RES_MENU_SAVE</source>
        <translation>Enregistrer</translation>
    </message>
    <message>
        <source>RES_MENU_NEW</source>
        <translation>Nouveau</translation>
    </message>
    <message>
        <source>RES_MENU_RECENT</source>
        <translation>Récent</translation>
    </message>
    <message>
        <source>RES_MENU_SHUTDOWN</source>
        <translation>Shut Down</translation>
    </message>
    <message>
        <source>RES_MENU_QUIT</source>
        <translation>Quit</translation>
    </message>
    <message>
        <source>RES_MENU_VIEW</source>
        <translation>Affichage</translation>
    </message>
    <message>
        <source>RES_MENU_NEXTPAGE</source>
        <translation>Page suivante</translation>
    </message>
    <message>
        <source>RES_MENU_PREVPAGE</source>
        <translation>Page précédente</translation>
    </message>
    <message>
        <source>RES_MENU_ZOOMIN</source>
        <translation>Zoom In</translation>
    </message>
    <message>
        <source>RES_MENU_ZOOMOUT</source>
        <translation>Zoom Out</translation>
    </message>
    <message>
        <source>RES_MENU_FITWIDTH</source>
        <translation>Ajuster la largeur</translation>
    </message>
    <message>
        <source>RES_MENU_FITHEIGHT</source>
        <translation>Ajuster la hauteur</translation>
    </message>
    <message>
        <source>RES_MENU_ROTATEDOC</source>
        <translation>Tourner le document</translation>
    </message>
    <message>
        <source>RES_MENU_REFLOW</source>
        <translation>Cycle Reflow Mode</translation>
    </message>
    <message>
        <source>RES_MENU_THUMBNAIL</source>
        <translation>Thumbnail</translation>
    </message>
    <message>
        <source>RES_MENU_DOCUMENT</source>
        <translation>Document</translation>
    </message>
    <message>
        <source>RES_MENU_GOTOPAGE</source>
        <translation>Atteindre la page</translation>
    </message>
    <message>
        <source>RES_MENU_GOTOELEMENT</source>
        <translation>Atteindre l'élément</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH</source>
        <translation>Rechercher</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_BACK</source>
        <translation>Search Backward</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_FORWARD</source>
        <translation>Search Forward</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_SNAP</source>
        <translation>Search Snap To Result</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_CANCEL</source>
        <translation>Cancel Search</translation>
    </message>
    <message>
        <source>RES_MENU_PAGE</source>
        <translation>Page Edit</translation>
    </message>
    <message>
        <source>RES_MENU_PAGEDELETE</source>
        <translation>Delete</translation>
    </message>
    <message>
        <source>RES_MENU_PAGEMOVEFORWARD</source>
        <translation>Move Forward</translation>
    </message>
    <message>
        <source>RES_MENU_PAGEMOVEBACKWARD</source>
        <translation>Move Backward</translation>
    </message>
    <message>
        <source>RES_MENU_PREFERENCES</source>
        <translation>Préférences</translation>
    </message>
    <message>
        <source>RES_MENU_HELP</source>
        <translation>Aide</translation>
    </message>
    <message>
        <source>RES_MENU_ABOUT</source>
        <translation>À propos de</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_ADD</source>
        <translation>Add Annotation</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_VIEW</source>
        <translation>View/Edit Annotation</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_DELETE</source>
        <translation>Delete Annotation</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_SAVE</source>
        <translation>Save Annotations</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_SHOW</source>
        <translation>Show Annotations</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_HIDE</source>
        <translation>Hide Annotations</translation>
    </message>
    <message>
        <source>RES_TITLE_GOTOPAGE</source>
        <translation>Atteindre la page</translation>
    </message>
    <message>
        <source>RES_HINT_GOTOPAGE</source>
        <translation>Numéro de page:</translation>
    </message>
    <message>
        <source>RES_TITLE_GOTOELEMENT</source>
        <translation>Atteindre l'élément</translation>
    </message>
    <message>
        <source>RES_HINT_GOTOELEMENT</source>
        <translation>No de l'élément, par ex « F5 »</translation>
    </message>
    <message>
        <source>RES_TITLE_SEARCH</source>
        <translation>Rechercher</translation>
    </message>
    <message>
        <source>RES_HINT_SEARCH</source>
        <translation>Rechercher la chaîne:</translation>
    </message>
    <message>
        <source>RES_TITLE_PASSWORD</source>
        <translation>Entrer le mot de passe</translation>
    </message>
    <message>
        <source>RES_HINT_PASSWORD</source>
        <translation>Mot de passe:</translation>
    </message>
    <message>
        <source>RES_OK</source>
        <translation>OK</translation>
    </message>
    <message>
        <source>RES_OPEN</source>
        <translation>Ouvrir</translation>
    </message>
    <message>
        <source>RES_YES</source>
        <translation>Oui</translation>
    </message>
    <message>
        <source>RES_NO</source>
        <translation>Non</translation>
    </message>
    <message>
        <source>RES_CANCEL</source>
        <translation>Annuler</translation>
    </message>
    <message>
        <source>RES_FULLSCREEN</source>
        <translation>Plein écran</translation>
    </message>
    <message>
        <source>RES_MEMORY_HEAP_KB</source>
        <translation>8192</translation>
    </message>
</context>
<context>
    <name>PrefDialog</name>
    <message>
        <source>RES_PREF_CAPTION</source>
        <translation>Préférences</translation>
    </message>
    <message>
        <source>RES_PREF_SINGLEPAGE</source>
        <translation>Charger page par page</translation>
    </message>
    <message>
        <source>RES_PREF_CHARENCODING</source>
        <translation>Jeu de caractères</translation>
    </message>
    <message>
        <source>RES_PREF_DEFENCODING</source>
        <translation>Par défaut</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO88591</source>
        <translation>Occidental (ISO 8859-1)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_BIG5</source>
        <translation>Chinois traditionnel (Big 5)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_GBK</source>
        <translation>Chinois simplifié (GBK)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_SHIFTJIS</source>
        <translation>Japonais (Shift JIS)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO2022JP</source>
        <translation>Japonais (ISO 2022-JP)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_EUCJP</source>
        <translation>Japonais (EUC-JP)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_WINDOWS949</source>
        <translation>Coréen (Windows CP 949)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_UTF8</source>
        <translation>Universel (UTF-8)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_WINDOWS1251</source>
        <translation>Windows (Windows CP 1251)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_KOI8</source>
        <translation>Cyrillique (KOI-8)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_WINDOWS866</source>
        <translation>DOS (Windows CP 866)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO88595</source>
        <translation>Cyrillique (ISO 8859-5)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO88597</source>
        <translation>Grec (ISO 8859-7)</translation>
    </message>
    <message>
        <source>RES_PREF_AUTOENCODING</source>
        <translation>Détection auto</translation>
    </message>
    <message>
        <source>RES_PREF_BASIC</source>
        <translation>Basic</translation>
    </message>
    <message>
        <source>RES_PREF_OTHER</source>
        <translation>Other</translation>
    </message>
    <message>
        <source>RES_PREF_MORE_PREFERENCES</source>
        <translation>More preferences...</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_PREFERENCES</source>
        <translation>OEM Preferences</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_NAME</source>
        <translation>Name</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_VALUE</source>
        <translation>Value</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_RESTART_WARNING</source>
        <translation>The application needs to be restarted before OEM preference changes can take effect.  Restart now?</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_PREF_FONT_COULD_NOT_BE_REGISTERED</source>
        <translation>Error: A font enabled in fileviewer.cfg could not be registered. Please check which languages are defined in the project make file.</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_PREF_FILE_NOT_FOUND</source>
        <translation>The fileviewer.cfg preferences file cannot be found in the current working directory. Preferences may not function correctly.</translation>
    </message>
</context>
<context>
    <name>HelpDialog</name>
    <message>
        <source>RES_HELP_CAPTION</source>
        <translation>Aide de Picsel Viewer</translation>
    </message>
    <message>
        <source>RES_HELP_UNKNOWN</source>
        <translation>Inconnu</translation>
    </message>
</context>
<context>
    <name>AboutDialog</name>
    <message>
        <source>RES_ABOUT_CAPTION</source>
        <translation>À propos de Picsel Viewer</translation>
    </message>
    <message>
        <source>RES_ABOUT_UNKNOWN</source>
        <translation>Inconnu</translation>
    </message>
    <message>
        <source>RES_ABOUTWOMARKUP_PART0</source>
        <translation>Picsel Viewer</translation>
    </message>
    <message>
        <source>RES_ABOUTWOMARKUP_PART1</source>
        <translation>(Issue </translation>
    </message>
    <message>
        <source>RES_ABOUTWOMARKUP_PART2</source>
        <translation>)</translation>
    </message>
    <message>
        <source>RES_ABOUT_PART0</source>
        <translation><![CDATA[<qt><h3>Picsel Viewer&trade;.</h3><em>Version ]]></translation>
    </message>
    <message>
        <source>RES_ABOUT_PART1</source>
        <translation> (Issue </translation>
    </message>
    <message>
        <source>RES_ABOUT_PART2</source>
        <translation><![CDATA[)|,/em|.|,p|.|,font size=2|.|,p|.|,p|.Powered by Picsel ePAGE|*reg; technology.|,br|.Copyright |*copy; Picsel 2000-2008.  All rights reserved.|,p|.|,hr|.This computer program, user interface and design are protected by international, US and European copyright laws. US and international Patents applied for. Picsel, Picsel Viewer, ePAGE and the Picsel cube logo are trademarks or registered trademarks of Picsel Technologies Ltd.|,p|.|,p|.This version of the Picsel Viewer has been licensed only for use by ]]></translation>
    </message>
    <message>
        <source>RES_ABOUT_PART3</source>
        <translation><![CDATA[.<p><hr><h4>Acknowledgements</h4><p>This software is based in part on the work of the independent JPEG group. <p>String library &copy; 1999-2000 Ralf S. Engelschall rse@engelschall.com.<p>This product includes software developed by the Apache Group for use in the Apache HTTP server project (http://www.apache.org/).<p>Parts of this software are derived from the RSA Data Security, Inc. MD5 Message-Digest Algorithm.<p>LZW decoder for GIF, &copy; 1987, by Steven A. Bennett.<p>'C' functions Copyright &copy; 1988, 1993 The Regents of the University of California.</qt>]]></translation>
    </message>
</context>
<context>
    <name>DirDialog</name>
    <message>
        <source>RES_DIR_CAPTION</source>
        <translation>Répertoire</translation>
    </message>
    <message>
        <source>RES_DIR_UNKNOWN</source>
        <translation>Inconnu</translation>
    </message>
</context>
<context>
    <name>Core</name>
    <message>
        <source>RES_ALERT_DOCTRANSLATIONFAILED</source>
        <translation>L'application ne peut pas afficher ce fichier</translation>
    </message>
    <message>
        <source>RES_ALERT_INTERNALERROR</source>
        <translation>Erreur interne</translation>
    </message>
    <message>
        <source>RES_ALERT_OUTOFMEMORY</source>
        <translation>Pas suffisamment de mémoire</translation>
    </message>
    <message>
        <source>RES_ALERT_UNKNOWNERROR</source>
        <translation>Erreur inconnue</translation>
    </message>
    <message>
        <source>RES_ALERT_DOCSAVEDSUCCESSFULLY</source>
        <translation>Le document a été enregistré avec succès</translation>
    </message>
    <message>
        <source>RES_ALERT_DOCSAVEERROR</source>
        <translation>Une erreur est apparue pendant la sauvegarde</translation>
    </message>
    <message>
        <source>RES_ALERT_SEARCHERROR</source>
        <translation>Erreur de recherche</translation>
    </message>
    <message>
        <source>RES_ALERT_SEARCHFAILED</source>
        <translation>Échec de la recherche – élément non trouvé</translation>
    </message>
    <message>
        <source>RES_ALERT_SEARCHWRAPPED</source>
        <translation>Recherche terminée – continuer ?</translation>
    </message>
    <message>
        <source>RES_ALERT_GOTOFAILED</source>
        <translation>Impossible d'aller à l'élément suivant – aucun élément trouvé</translation>
    </message>
    <message>
        <source>RES_ALERT_GOTOERROR</source>
        <translation>Impossible d'aller à l'élément</translation>
    </message>
    <message>
        <source>RES_ALERT_NOTHINGSELECTED</source>
        <translation>Aucune sélection effectuée</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTOEDIT</source>
        <translation>Impossible d'éditer cette sélection</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTODELETE</source>
        <translation>Suppression échouée</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTOINSERT</source>
        <translation>Insertion échouée</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTOUPDATE</source>
        <translation>Mise à jour du document échouée</translation>
    </message>
    <message>
        <source>RES_ALERT_COULDNOTINSERTHERE</source>
        <translation>Impossible d'insérer ici</translation>
    </message>
    <message>
        <source>RES_ALERT_COULDNOTINSERTMAX</source>
        <translation>Impossible d'insérer – le document a atteint sa taille maximum</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTODESELECT</source>
        <translation>Impossible de désélectionner. Essayez à nouveau ou rechargez le document</translation>
    </message>
    <message>
        <source>RES_ALERT_INVALIDFONTSIZE</source>
        <translation>Taille de la police invalide. Les tailles valides vont de 2 à 144 pts</translation>
    </message>
    <message>
        <source>RES_ALERT_INVALIDFORMATSTRING</source>
        <translation>Format de chaîne de caractère invalide</translation>
    </message>
    <message>
        <source>RES_ALERT_DOCNOTEDITABLE</source>
        <translation>Ce document ne peut pas être édité</translation>
    </message>
    <message>
        <source>RES_ALERT_ERRORINFORMULA</source>
        <translation>Une formule Excel a retourné une erreur</translation>
    </message>
    <message>
        <source>RES_ALERT_FORMULAUNSUPPORTED</source>
        <translation>Impossible d'analyser la formule</translation>
    </message>
    <message>
        <source>RES_ALERT_CIRCULARDEPENDENCY</source>
        <translation>Référence circulaire dans la formule</translation>
    </message>
    <message>
        <source>RES_ALERT_ARRAYNOTSUPPORTED</source>
        <translation>La mise à jour de la matrice ou du tableau n'est pas supportée</translation>
    </message>
    <message>
        <source>RES_ALERT_SORTFAILED</source>
        <translation>Sorting has failed</translation>
    </message>
    <message>
        <source>RES_ALERT_INVALIDGOTO</source>
        <translation>La valeur spécifiée ne semble pas pointer vers une cellule</translation>
    </message>
    <message>
        <source>RES_ALERT_FORMULASUNSUPPORTED</source>
        <translation>Le document contient des formules non supportées par Picsel.
Il n'est pas possible d'éditer ce document.</translation>
    </message>
    <message>
        <source>RES_ALERT_IMAGESUBSAMPLED</source>
        <translation>Images within the document have been subsampled to conserve memory</translation>
    </message>
    <message>
        <source>RES_ALERT_TABLERESTRICTION</source>
        <translation>Row/column insertion/deletion is not allowed within a table or pivot table</translation>
    </message>
    <message>
        <source>RES_ALERT_ANNOTATION_SAVED</source>
        <translation>Annotations have been saved</translation>
    </message>
    <message>
        <source>RES_CONFIRM_ANNOTATION_LOAD</source>
        <translation>Annotation file found.  Load it?</translation>
    </message>
    <message>
        <source>RES_CONFIRM_OPENNEW</source>
        <translation>Vous avez édité ce document.
Désirez-vous vraiment ouvrir ce nouveau document et perdre vos modifications ?</translation>
    </message>
    <message>
        <source>RES_CONFIRM_CONFIRMQUIT</source>
        <translation>Vous avez édité ce document.
Voulez-vous vraiment quitter et perdre vos modifications ?</translation>
    </message>
    <message>
        <source>RES_CONFIRM_CONTENTLOSS</source>
        <translation>Le document original n'est pas présent, si vous enregistrez le document maintenant, les images seront perdues.
Voulez-vous continuer ?</translation>
    </message>
</context>
</TS>
