<!-- auto-generated by ./tsv2ts.pl from picseledit.csv on Thu Sep 24 14:15:51 2009 -->

<!-- Copyright (C) Picsel, 2007. All Rights Reserved. -->

<!-- @author Picsel Technologies Ltd -->

<!-- $Id: picseledit-pt-br.ts,v 1.19 2009/09/28 10:46:59 neilk Exp $ -->

<!DOCTYPE TS><TS>
<context>
    <name>ContentsEditDialog</name>
    <message>
        <source>RES_CED_Brazil</source>
        <translation>Brasil</translation>
    </message>
    <message>
        <source>RES_CED_Uruguay</source>
        <translation>Uruguai</translation>
    </message>
    <message>
        <source>RES_CED_Argentina</source>
        <translation>Argentina</translation>
    </message>
    <message>
        <source>RES_CED_Colombia</source>
        <translation>Colômbia</translation>
    </message>
    <message>
        <source>RES_CED_Guatemala</source>
        <translation>Guatemala</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia</source>
        <translation>Bolívia</translation>
    </message>
    <message>
        <source>RES_CED_Chile</source>
        <translation>Chile</translation>
    </message>
    <message>
        <source>RES_CED_DominicanRepublic</source>
        <translation>República Dominicana</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador</source>
        <translation>Equador</translation>
    </message>
    <message>
        <source>RES_CED_Mexico</source>
        <translation>México</translation>
    </message>
    <message>
        <source>RES_CED_Peru</source>
        <translation>Peru</translation>
    </message>
    <message>
        <source>RES_CED_Paraguay</source>
        <translation>Paraguai</translation>
    </message>
    <message>
        <source>RES_CED_ElSalvador</source>
        <translation>El Salvador</translation>
    </message>
    <message>
        <source>RES_CED_TrinidadTobago</source>
        <translation>Trinidad e Tobago</translation>
    </message>
    <message>
        <source>RES_CED_Honduras</source>
        <translation>Honduras</translation>
    </message>
    <message>
        <source>RES_CED_Nicaragua</source>
        <translation>Nicarágua</translation>
    </message>
    <message>
        <source>RES_CED_Venezuela</source>
        <translation>Venezuela</translation>
    </message>
    <message>
        <source>RES_CED_Panama</source>
        <translation>Panamá</translation>
    </message>
    <message>
        <source>RES_CED_CostaRica</source>
        <translation>Costa Rica</translation>
    </message>
    <message>
        <source>RES_CED_Jamaica</source>
        <translation>Jamaica</translation>
    </message>
    <message>
        <source>RES_CED_FrenchCanada</source>
        <translation>Canadá Francês</translation>
    </message>
    <message>
        <source>RES_CED_UnitedKingdom</source>
        <translation>Reino Unido</translation>
    </message>
    <message>
        <source>RES_CED_UnitedStates</source>
        <translation>Estados Unidos</translation>
    </message>
    <message>
        <source>RES_CED_ISO</source>
        <translation>ISO</translation>
    </message>
    <message>
        <source>RES_CED_Local</source>
        <translation>Local</translation>
    </message>
    <message>
        <source>RES_CED_HongKong</source>
        <translation>Hong Kong</translation>
    </message>
    <message>
        <source>RES_CED_Taiwan</source>
        <translation>Taiwan</translation>
    </message>
    <message>
        <source>RES_CED_Indonesia</source>
        <translation>Indonesia</translation>
    </message>
    <message>
        <source>RES_CED_Malaysia</source>
        <translation>Malaysia</translation>
    </message>
    <message>
        <source>RES_CED_Philippines</source>
        <translation>Philippines</translation>
    </message>
    <message>
        <source>RES_CED_Thailand</source>
        <translation>Thailand</translation>
    </message>
    <message>
        <source>RES_CED_Vietnam</source>
        <translation>Vietnam</translation>
    </message>
    <message>
        <source>RES_CED_Brazil_Real</source>
        <translation>Brasil: Real</translation>
    </message>
    <message>
        <source>RES_CED_Uruguay_Peso</source>
        <translation>Uruguai: Peso</translation>
    </message>
    <message>
        <source>RES_CED_Argentina_Peso</source>
        <translation>Argentina: Peso</translation>
    </message>
    <message>
        <source>RES_CED_Colombia_Peso</source>
        <translation>Colômbia: Peso</translation>
    </message>
    <message>
        <source>RES_CED_Guatemala_Quetzal</source>
        <translation>Guatemala: Quetzal</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia_Boliviano_Quechua</source>
        <translation>Bolívia: Boliviano (Quéchua)</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia_Boliviano_Spanish</source>
        <translation>Bolívia: Boliviano (Espanhol)</translation>
    </message>
    <message>
        <source>RES_CED_Chile_Peso</source>
        <translation>Chile: Peso</translation>
    </message>
    <message>
        <source>RES_CED_DominicanRepublic_Peso</source>
        <translation>República Dominicana: Peso</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador_Sucre_Quechua</source>
        <translation>Equador: Sucre (Quéchua)</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador_Sucre_Spanish</source>
        <translation>Equador: Sucre (Espanhol)</translation>
    </message>
    <message>
        <source>RES_CED_Mexico_Peso</source>
        <translation>México: Peso</translation>
    </message>
    <message>
        <source>RES_CED_Peru_NuevoSol_Quechua</source>
        <translation>Peru: Sol Novo (Quéchua)</translation>
    </message>
    <message>
        <source>RES_CED_Peru_NuevoSol_Spanish</source>
        <translation>Peru: Sol Novo (Espanhol)</translation>
    </message>
    <message>
        <source>RES_CED_Paraguay_Guarani</source>
        <translation>Paraguai: Guarani</translation>
    </message>
    <message>
        <source>RES_CED_ElSalvador_Colon</source>
        <translation>El Salvador: Colón</translation>
    </message>
    <message>
        <source>RES_CED_TrinidadTobago_Dollar</source>
        <translation>Trinidad e Tobago: Dólar</translation>
    </message>
    <message>
        <source>RES_CED_Honduras_Lempira</source>
        <translation>Honduras: Lempira</translation>
    </message>
    <message>
        <source>RES_CED_Nicaragua_Cordoba</source>
        <translation>Nicarágua: Córdoba</translation>
    </message>
    <message>
        <source>RES_CED_Venezuela_Bolivar</source>
        <translation>Venezuela: Bolívar</translation>
    </message>
    <message>
        <source>RES_CED_Panama_Balboa</source>
        <translation>Panamá: Balboa</translation>
    </message>
    <message>
        <source>RES_CED_CostaRica_Colon</source>
        <translation>Costa Rica: Colón</translation>
    </message>
    <message>
        <source>RES_CED_Jamaica_Dollar</source>
        <translation>Jamaica: Dólar</translation>
    </message>
    <message>
        <source>RES_CED_FrenchCanada_Dollar</source>
        <translation>Canadá Francês: Dólar</translation>
    </message>
    <message>
        <source>RES_CED_Sterling</source>
        <translation>Esterlina</translation>
    </message>
    <message>
        <source>RES_CED_UnitedKingdom_Pound</source>
        <translation>Reino Unido: Libra</translation>
    </message>
    <message>
        <source>RES_CED_UnitedStates_Dollar</source>
        <translation>Estados Unidos: Dólar</translation>
    </message>
    <message>
        <source>RES_CED_Euro</source>
        <translation>Euro</translation>
    </message>
    <message>
        <source>RES_CED_Euro_Alt</source>
        <translation>Euro (Alt)</translation>
    </message>
    <message>
        <source>RES_CED_HongKong_Dollar</source>
        <translation>Hong Kong : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Taiwan_Dollar</source>
        <translation>Taiwan : Dollar</translation>
    </message>
    <message>
        <source>RES_CED_Indonesia_Rupiah</source>
        <translation>Indonesia : Rupiah</translation>
    </message>
    <message>
        <source>RES_CED_Malaysia_Ringgit</source>
        <translation>Malaysia : Ringgit</translation>
    </message>
    <message>
        <source>RES_CED_Philippines_Peso</source>
        <translation>Philippines : Peso</translation>
    </message>
    <message>
        <source>RES_CED_Thailand_Baht</source>
        <translation>Thailand : Baht</translation>
    </message>
    <message>
        <source>RES_CED_Vietnam_Dong</source>
        <translation>Vietnam : Dong</translation>
    </message>
    <message>
        <source>RES_CED_Brazil_Real_Name</source>
        <translation>Brasil: Real (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Uruguay_Peso_Name</source>
        <translation>Uruguai: Peso (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Argentina_Peso_Name</source>
        <translation>Argentina: Peso (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Colombia_Peso_Name</source>
        <translation>Colômbia: Peso (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Guatemala_Quetzal_Name</source>
        <translation>Guatemala: Quetzal (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Bolivia_Boliviano_Name</source>
        <translation>Bolívia: Boliviano (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Chile_Peso_Name</source>
        <translation>Chile: Peso (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_DominicanRepublic_Peso_Name</source>
        <translation>República Dominicana: Peso (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Ecuador_Sucre_Name</source>
        <translation>Equador: Sucre (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Mexico_Peso_Name</source>
        <translation>México: Peso (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Peru_NuevoSol_Name</source>
        <translation>Peru: Sol Novo (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Paraguay_Guarani_Name</source>
        <translation>Paraguai: Guarani (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_ElSalvador_Colon_Name</source>
        <translation>El Salvador: Colón (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_TrinidadTobago_Dollar_Name</source>
        <translation>Trinidad e Tobago: Dólar (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Honduras_Lempira_Name</source>
        <translation>Honduras: Lempira (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Nicaragua_Cordoba_Name</source>
        <translation>Nicarágua: Córdoba (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Venezuela_Bolivar_Name</source>
        <translation>Venezuela: Bolívar (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Panama_Balboa_Name</source>
        <translation>Panamá: Balboa (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_CostaRica_Colon_Name</source>
        <translation>Costa Rica: Colón (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Haiti_Gourde_Name</source>
        <translation>Haiti: Gourde (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Jamaica_Dollar_Name</source>
        <translation>Jamaica: Dólar (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_UnitedKingdom_Pound_Name</source>
        <translation>Reino Unido: Libra (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_UnitedStates_Dollar_Name</source>
        <translation>Estados Unidos: Dólar (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_Euro_Name</source>
        <translation>Euro (Nome)</translation>
    </message>
    <message>
        <source>RES_CED_HongKong_Dollar_Name</source>
        <translation>Hong Kong : Dollar (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Taiwan_Dollar_Name</source>
        <translation>Taiwan : Dollar (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Indonesia_Rupiah_Name</source>
        <translation>Indonesia : Rupiah (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Malaysia_Ringgit_Name</source>
        <translation>Malaysia : Ringgit (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Philippines_Peso_Name</source>
        <translation>Philippines : Peso (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Thailand_Baht_Name</source>
        <translation>Thailand : Baht (Name)</translation>
    </message>
    <message>
        <source>RES_CED_Vietnam_Dong_Name</source>
        <translation>Vietnam : Dong (Name)</translation>
    </message>
    <message>
        <source>RES_CED_NEG1</source>
        <translation>Usar - sinal -vo</translation>
    </message>
    <message>
        <source>RES_CED_NEG2</source>
        <translation>Não - sinal -vo, vermelho</translation>
    </message>
    <message>
        <source>RES_CED_NEG3</source>
        <translation>Usar - sinal -vo, indentar</translation>
    </message>
    <message>
        <source>RES_CED_NEG4</source>
        <translation>Usar - sinal -vo, vermelho, indentar</translation>
    </message>
    <message>
        <source>RES_CED_DP0</source>
        <translation>Nenhuma casa decimal</translation>
    </message>
    <message>
        <source>RES_CED_DP1</source>
        <translation>Uma casa decimal</translation>
    </message>
    <message>
        <source>RES_CED_DP2</source>
        <translation>Duas casas decimais</translation>
    </message>
    <message>
        <source>RES_CED_DP3</source>
        <translation>Três casas decimais</translation>
    </message>
    <message>
        <source>RES_CED_DP10</source>
        <translation>Dez casas decimais</translation>
    </message>
    <message>
        <source>RES_CED_NOCOMMAS</source>
        <translation>Sem vírgula</translation>
    </message>
    <message>
        <source>RES_CED_COMMAS</source>
        <translation>Vírgulas</translation>
    </message>
    <message>
        <source>RES_CED_LONGDATEFORMAT</source>
        <translation>Data Formal</translation>
    </message>
    <message>
        <source>RES_CED_DATEFORMAT</source>
        <translation>Data</translation>
    </message>
    <message>
        <source>RES_CED_TIMEFORMAT</source>
        <translation>Hora</translation>
    </message>
    <message>
        <source>RES_CED_DATETIMEFORMAT</source>
        <translation>Data e Hora</translation>
    </message>
    <message>
        <source>RES_CED_FRAC1</source>
        <translation>Máximo de um Dígito</translation>
    </message>
    <message>
        <source>RES_CED_FRAC2</source>
        <translation>Máximo de dois Dígitos</translation>
    </message>
    <message>
        <source>RES_CED_FRAC3</source>
        <translation>Máximo de três Dígitos</translation>
    </message>
    <message>
        <source>RES_CED_FRAC4</source>
        <translation>Em Metade</translation>
    </message>
    <message>
        <source>RES_CED_FRAC5</source>
        <translation>Em Quartos</translation>
    </message>
    <message>
        <source>RES_CED_FRAC6</source>
        <translation>Em Oitavos</translation>
    </message>
    <message>
        <source>RES_CED_FRAC7</source>
        <translation>Em Dezesseis Avos</translation>
    </message>
    <message>
        <source>RES_CED_FRAC8</source>
        <translation>Em Décimos</translation>
    </message>
    <message>
        <source>RES_CED_FRAC9</source>
        <translation>Em Centésimos</translation>
    </message>
    <message>
        <source>RES_CED_GENERAL</source>
        <translation>Geral</translation>
    </message>
    <message>
        <source>RES_CED_NUMBER</source>
        <translation>Número</translation>
    </message>
    <message>
        <source>RES_CED_CURRENCY</source>
        <translation>Moeda</translation>
    </message>
    <message>
        <source>RES_CED_ACCOUNTING</source>
        <translation>Contábil</translation>
    </message>
    <message>
        <source>RES_CED_DATE</source>
        <translation>Data</translation>
    </message>
    <message>
        <source>RES_CED_TIME</source>
        <translation>Hora</translation>
    </message>
    <message>
        <source>RES_CED_PERCENTAGE</source>
        <translation>Porcentagem</translation>
    </message>
    <message>
        <source>RES_CED_FRACTION</source>
        <translation>Fração</translation>
    </message>
    <message>
        <source>RES_CED_SCIENTIFIC</source>
        <translation>Científico</translation>
    </message>
    <message>
        <source>RES_CED_TEXT</source>
        <translation>Texto</translation>
    </message>
    <message>
        <source>RES_CED_CUSTOM</source>
        <translation>Personalizado</translation>
    </message>
    <message>
        <source>RES_CED_NOACTION</source>
        <translation>No action</translation>
    </message>
    <message>
        <source>RES_CED_INSERTROWBEFORE</source>
        <translation>Inserir linha antes</translation>
    </message>
    <message>
        <source>RES_CED_INSERTCOLUMNBEFORE</source>
        <translation>Inserir coluna antes</translation>
    </message>
    <message>
        <source>RES_CED_INSERTTABLE</source>
        <translation>Insert Table</translation>
    </message>
    <message>
        <source>RES_CED_DELETECURRENTROW</source>
        <translation>Excluir linha atual</translation>
    </message>
    <message>
        <source>RES_CED_DELETECURRENTCOLUMN</source>
        <translation>Excluir coluna atual</translation>
    </message>
    <message>
        <source>RES_CED_DELETETABLE</source>
        <translation>Excluir tabela</translation>
    </message>
    <message>
        <source>RES_CED_TITLE</source>
        <translation>Editar </translation>
    </message>
    <message>
        <source>RES_CED_REPLACE</source>
        <translation>Replace</translation>
    </message>
    <message>
        <source>RES_CED_INSERTABOVE</source>
        <translation>Insert Above</translation>
    </message>
    <message>
        <source>RES_CED_INSERTBELOW</source>
        <translation>Insert Below</translation>
    </message>
    <message>
        <source>RES_CED_STYLE</source>
        <translation>Estilo:</translation>
    </message>
    <message>
        <source>RES_CED_SIZE</source>
        <translation>Tamanho:</translation>
    </message>
    <message>
        <source>RES_CED_COLOUR</source>
        <translation>Cor:</translation>
    </message>
    <message>
        <source>RES_CED_HIGHLIGHT</source>
        <translation>Destacar:</translation>
    </message>
    <message>
        <source>RES_CED_FONT</source>
        <translation>Fonte:</translation>
    </message>
    <message>
        <source>RES_CED_FORMAT</source>
        <translation>Formato:</translation>
    </message>
    <message>
        <source>RES_CED_RESIZEWIDTH</source>
        <translation>Largura:</translation>
    </message>
    <message>
        <source>RES_CED_RESIZEHEIGHT</source>
        <translation>Altura:</translation>
    </message>
    <message>
        <source>RES_CED_AUTOFIT</source>
        <translation>Ajustar</translation>
    </message>
    <message>
        <source>RES_CED_LAYOUT</source>
        <translation>Layout:</translation>
    </message>
    <message>
        <source>RES_CED_LAYLEFT</source>
        <translation>Esquerda</translation>
    </message>
    <message>
        <source>RES_CED_LAYHCENTRE</source>
        <translation>Centro</translation>
    </message>
    <message>
        <source>RES_CED_LAYRIGHT</source>
        <translation>Direita</translation>
    </message>
    <message>
        <source>RES_CED_LAYTOP</source>
        <translation>Topo</translation>
    </message>
    <message>
        <source>RES_CED_LAYVCENTRE</source>
        <translation>Centro</translation>
    </message>
    <message>
        <source>RES_CED_LAYBOTTOM</source>
        <translation>Inferior</translation>
    </message>
    <message>
        <source>RES_CED_INDENT</source>
        <translation>Indent:</translation>
    </message>
    <message>
        <source>RES_CED_STYLEFONTMENU</source>
        <translation>Estilo/Fonte</translation>
    </message>
    <message>
        <source>RES_CED_FORMATLAYOUTMENU</source>
        <translation>Formato/Layout</translation>
    </message>
    <message>
        <source>RES_CED_RESIZEMENU</source>
        <translation>Redefinir</translation>
    </message>
    <message>
        <source>RES_CED_INSERTDELETEMENU</source>
        <translation>Inserir/Excluir</translation>
    </message>
    <message>
        <source>RES_CED_HYPERLINKMENU</source>
        <translation>Link</translation>
    </message>
    <message>
        <source>RES_CED_HYPERLINKURL</source>
        <translation>URL do link:</translation>
    </message>
    <message>
        <source>RES_CED_BULLETNUMBERMENU</source>
        <translation>Marcadores e numeração</translation>
    </message>
    <message>
        <source>RES_CED_RENUMBER</source>
        <translation>Reiniciar numeração</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTART</source>
        <translation>Iniciar em:</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPE</source>
        <translation>Tipo de lista:</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPENONE</source>
        <translation>Nenhum</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPEBULLET</source>
        <translation>Com marcadores</translation>
    </message>
    <message>
        <source>RES_CED_LISTTYPENUMBER</source>
        <translation>Numerada</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLE</source>
        <translation>Estilo:</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLEAUTO</source>
        <translation>Automático</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLEDASH</source>
        <translation>Traço</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLEDOT</source>
        <translation>Ponto</translation>
    </message>
    <message>
        <source>RES_CED_LISTSTYLESQUARE</source>
        <translation>Quadrado</translation>
    </message>
    <message>
        <source>RES_CED_NOCOLOUR</source>
        <translation>(Nenhum)</translation>
    </message>
    <message>
        <source>RES_CED_COLOURPICKER</source>
        <translation>Cor</translation>
    </message>
    <message>
        <source>RES_CED_SORTCELLS</source>
        <translation>Sort cells</translation>
    </message>
    <message>
        <source>RES_CED_CASESENSITIVE</source>
        <translation>Case Sensitive</translation>
    </message>
    <message>
        <source>RES_CED_SORTASCENDING</source>
        <translation>Ascending</translation>
    </message>
    <message>
        <source>RES_CED_SORTBYCOL</source>
        <translation>Sort by column</translation>
    </message>
    <message>
        <source>RES_CED_SORTBYROW</source>
        <translation>Sort by row</translation>
    </message>
    <message>
        <source>RES_CED_SORTBY_FIRST</source>
        <translation>First sort by</translation>
    </message>
    <message>
        <source>RES_CED_SORTBY_SECOND</source>
        <translation>Then sort by</translation>
    </message>
    <message>
        <source>RES_CED_SORTBY_LAST</source>
        <translation>Finally sort by</translation>
    </message>
    <message>
        <source>RES_CED_SORTNEXT</source>
        <translation>First corner selected, now select second corner for sort range</translation>
    </message>
    <message>
        <source>RES_CED_SORTMENU</source>
        <translation>Sort</translation>
    </message>
</context>
<context>
    <name>FunctionNames</name>
    <message>
        <source>RES_FUNC_NOW</source>
        <translation>AGORA</translation>
    </message>
    <message>
        <source>RES_FUNC_FV</source>
        <translation>FV</translation>
    </message>
    <message>
        <source>RES_FUNC_IRR</source>
        <translation>MTIR</translation>
    </message>
    <message>
        <source>RES_FUNC_NPER</source>
        <translation>NPER</translation>
    </message>
    <message>
        <source>RES_FUNC_NPV</source>
        <translation>VAL</translation>
    </message>
    <message>
        <source>RES_FUNC_PMT</source>
        <translation>PGTO</translation>
    </message>
    <message>
        <source>RES_FUNC_PV</source>
        <translation>VA</translation>
    </message>
    <message>
        <source>RES_FUNC_RATE</source>
        <translation>TAXA</translation>
    </message>
    <message>
        <source>RES_FUNC_AND</source>
        <translation>E</translation>
    </message>
    <message>
        <source>RES_FUNC_FALSE</source>
        <translation>FALSO</translation>
    </message>
    <message>
        <source>RES_FUNC_IF</source>
        <translation>SE</translation>
    </message>
    <message>
        <source>RES_FUNC_NOT</source>
        <translation>NÃO</translation>
    </message>
    <message>
        <source>RES_FUNC_OR</source>
        <translation>OU</translation>
    </message>
    <message>
        <source>RES_FUNC_TRUE</source>
        <translation>VERDADEIRO</translation>
    </message>
    <message>
        <source>RES_FUNC_ABS</source>
        <translation>ABS</translation>
    </message>
    <message>
        <source>RES_FUNC_INT</source>
        <translation>INT</translation>
    </message>
    <message>
        <source>RES_FUNC_LN</source>
        <translation>LN</translation>
    </message>
    <message>
        <source>RES_FUNC_LOG</source>
        <translation>LOG</translation>
    </message>
    <message>
        <source>RES_FUNC_LOG10</source>
        <translation>LOG10</translation>
    </message>
    <message>
        <source>RES_FUNC_MOD</source>
        <translation>MOD</translation>
    </message>
    <message>
        <source>RES_FUNC_POWER</source>
        <translation>POTÊNCIA</translation>
    </message>
    <message>
        <source>RES_FUNC_PRODUCT</source>
        <translation>PRODUTO</translation>
    </message>
    <message>
        <source>RES_FUNC_ROUND</source>
        <translation>ARRED</translation>
    </message>
    <message>
        <source>RES_FUNC_SQRT</source>
        <translation>RAIZQ</translation>
    </message>
    <message>
        <source>RES_FUNC_SUM</source>
        <translation>SOMA</translation>
    </message>
    <message>
        <source>RES_FUNC_SUMIF</source>
        <translation>SOMA.SE</translation>
    </message>
    <message>
        <source>RES_FUNC_TRUNC</source>
        <translation>TRUNCAR</translation>
    </message>
    <message>
        <source>RES_FUNC_AVERAGE</source>
        <translation>MÉDIA</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNTIF</source>
        <translation>CONTAR.SE</translation>
    </message>
    <message>
        <source>RES_FUNC_MAX</source>
        <translation>MÁX</translation>
    </message>
    <message>
        <source>RES_FUNC_MIN</source>
        <translation>MÍN</translation>
    </message>
    <message>
        <source>RES_FUNC_DATE</source>
        <translation>DATA</translation>
    </message>
    <message>
        <source>RES_FUNC_TIME</source>
        <translation>HORA</translation>
    </message>
    <message>
        <source>RES_FUNC_DATEVALUE</source>
        <translation>DATA.VALOR</translation>
    </message>
    <message>
        <source>RES_FUNC_TIMEVALUE</source>
        <translation>VALOR.TEMPO</translation>
    </message>
    <message>
        <source>RES_FUNC_HOUR</source>
        <translation>HORA</translation>
    </message>
    <message>
        <source>RES_FUNC_MINUTE</source>
        <translation>MINUTO</translation>
    </message>
    <message>
        <source>RES_FUNC_SECOND</source>
        <translation>SEGUNDO</translation>
    </message>
    <message>
        <source>RES_FUNC_DAY</source>
        <translation>DIA</translation>
    </message>
    <message>
        <source>RES_FUNC_MONTH</source>
        <translation>MÊS</translation>
    </message>
    <message>
        <source>RES_FUNC_YEAR</source>
        <translation>ANO</translation>
    </message>
    <message>
        <source>RES_FUNC_DDB</source>
        <translation>BDD</translation>
    </message>
    <message>
        <source>RES_FUNC_SLN</source>
        <translation>DPD</translation>
    </message>
    <message>
        <source>RES_FUNC_SYD</source>
        <translation>SDA</translation>
    </message>
    <message>
        <source>RES_FUNC_STDEV</source>
        <translation>DESVPA</translation>
    </message>
    <message>
        <source>RES_FUNC_STDEVP</source>
        <translation>DESVPADP</translation>
    </message>
    <message>
        <source>RES_FUNC_VAR</source>
        <translation>VAR</translation>
    </message>
    <message>
        <source>RES_FUNC_VARP</source>
        <translation>VARP</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNT</source>
        <translation>CONT.NÚM</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNTA</source>
        <translation>CONT.VALORES</translation>
    </message>
    <message>
        <source>RES_FUNC_COUNTBLANK</source>
        <translation>CONTAR.VAZIO</translation>
    </message>
</context>
<context>
    <name>DateTime</name>
    <message>
        <source>RES_TIMEDATE_LONGDATEFORMAT</source>
        <translation>dd mmmm yyyy</translation>
    </message>
    <message>
        <source>RES_TIMEDATE_DATEFORMAT</source>
        <translation>dd/mm/yyyy</translation>
    </message>
    <message>
        <source>RES_TIMEDATE_TIMEFORMAT</source>
        <translation>hh:mm</translation>
    </message>
    <message>
        <source>RES_TIMEDATE_DATETIMEFORMAT</source>
        <translation>dd/mm/yyyy hh:mm</translation>
    </message>
    <message>
        <source>RES_DAY_1</source>
        <translation>Domingo</translation>
    </message>
    <message>
        <source>RES_DAY_2</source>
        <translation>Segunda</translation>
    </message>
    <message>
        <source>RES_DAY_3</source>
        <translation>Terça</translation>
    </message>
    <message>
        <source>RES_DAY_4</source>
        <translation>Quarta</translation>
    </message>
    <message>
        <source>RES_DAY_5</source>
        <translation>Quinta</translation>
    </message>
    <message>
        <source>RES_DAY_6</source>
        <translation>Sexta</translation>
    </message>
    <message>
        <source>RES_DAY_7</source>
        <translation>Sábado</translation>
    </message>
    <message>
        <source>RES_DAYABBR_1</source>
        <translation>Dom</translation>
    </message>
    <message>
        <source>RES_DAYABBR_2</source>
        <translation>Seg</translation>
    </message>
    <message>
        <source>RES_DAYABBR_3</source>
        <translation>Ter</translation>
    </message>
    <message>
        <source>RES_DAYABBR_4</source>
        <translation>Qua</translation>
    </message>
    <message>
        <source>RES_DAYABBR_5</source>
        <translation>Qui</translation>
    </message>
    <message>
        <source>RES_DAYABBR_6</source>
        <translation>Sex</translation>
    </message>
    <message>
        <source>RES_DAYABBR_7</source>
        <translation>Sáb</translation>
    </message>
    <message>
        <source>RES_MONTH_1</source>
        <translation>Janeiro</translation>
    </message>
    <message>
        <source>RES_MONTH_2</source>
        <translation>Fevereiro</translation>
    </message>
    <message>
        <source>RES_MONTH_3</source>
        <translation>Março</translation>
    </message>
    <message>
        <source>RES_MONTH_4</source>
        <translation>Abril</translation>
    </message>
    <message>
        <source>RES_MONTH_5</source>
        <translation>Maio</translation>
    </message>
    <message>
        <source>RES_MONTH_6</source>
        <translation>Junho</translation>
    </message>
    <message>
        <source>RES_MONTH_7</source>
        <translation>Julho</translation>
    </message>
    <message>
        <source>RES_MONTH_8</source>
        <translation>Agosto</translation>
    </message>
    <message>
        <source>RES_MONTH_9</source>
        <translation>Setembro</translation>
    </message>
    <message>
        <source>RES_MONTH_10</source>
        <translation>Outubro</translation>
    </message>
    <message>
        <source>RES_MONTH_11</source>
        <translation>Novembro</translation>
    </message>
    <message>
        <source>RES_MONTH_12</source>
        <translation>Dezembro</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_1</source>
        <translation>Jan</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_2</source>
        <translation>Fev</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_3</source>
        <translation>Mar</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_4</source>
        <translation>Abr</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_5</source>
        <translation>Mai</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_6</source>
        <translation>Jun</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_7</source>
        <translation>Jul</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_8</source>
        <translation>Ago</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_9</source>
        <translation>Set</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_10</source>
        <translation>Out</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_11</source>
        <translation>Nov</translation>
    </message>
    <message>
        <source>RES_MONTHABBR_12</source>
        <translation>Dez</translation>
    </message>
    <message>
        <source>RES_AMPM_1</source>
        <translation>am</translation>
    </message>
    <message>
        <source>RES_AMPM_2</source>
        <translation>pm</translation>
    </message>
</context>
<context>
    <name>MainWidgetCommon</name>
    <message>
        <source>RES_MENU_FILE</source>
        <translation>Arquivo</translation>
    </message>
    <message>
        <source>RES_MENU_OPEN</source>
        <translation>Abrir</translation>
    </message>
    <message>
        <source>RES_MENU_SAVE</source>
        <translation>Salvar</translation>
    </message>
    <message>
        <source>RES_MENU_NEW</source>
        <translation>Novo</translation>
    </message>
    <message>
        <source>RES_MENU_RECENT</source>
        <translation>Recente</translation>
    </message>
    <message>
        <source>RES_MENU_SHUTDOWN</source>
        <translation>Shut Down</translation>
    </message>
    <message>
        <source>RES_MENU_QUIT</source>
        <translation>Quit</translation>
    </message>
    <message>
        <source>RES_MENU_VIEW</source>
        <translation>Exibir</translation>
    </message>
    <message>
        <source>RES_MENU_NEXTPAGE</source>
        <translation>Próxima Página</translation>
    </message>
    <message>
        <source>RES_MENU_PREVPAGE</source>
        <translation>Página Anterior</translation>
    </message>
    <message>
        <source>RES_MENU_ZOOMIN</source>
        <translation>Zoom In</translation>
    </message>
    <message>
        <source>RES_MENU_ZOOMOUT</source>
        <translation>Zoom Out</translation>
    </message>
    <message>
        <source>RES_MENU_FITWIDTH</source>
        <translation>Ajustar Largura</translation>
    </message>
    <message>
        <source>RES_MENU_FITHEIGHT</source>
        <translation>Ajusar Altura</translation>
    </message>
    <message>
        <source>RES_MENU_ROTATEDOC</source>
        <translation>Girar Documento</translation>
    </message>
    <message>
        <source>RES_MENU_REFLOW</source>
        <translation>Cycle Reflow Mode</translation>
    </message>
    <message>
        <source>RES_MENU_THUMBNAIL</source>
        <translation>Thumbnail</translation>
    </message>
    <message>
        <source>RES_MENU_DOCUMENT</source>
        <translation>Documento</translation>
    </message>
    <message>
        <source>RES_MENU_GOTOPAGE</source>
        <translation>Ir para Página</translation>
    </message>
    <message>
        <source>RES_MENU_GOTOELEMENT</source>
        <translation>Ir para Elemento</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH</source>
        <translation>Pesquisar</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_BACK</source>
        <translation>Search Backward</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_FORWARD</source>
        <translation>Search Forward</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_SNAP</source>
        <translation>Search Snap To Result</translation>
    </message>
    <message>
        <source>RES_MENU_SEARCH_CANCEL</source>
        <translation>Cancel Search</translation>
    </message>
    <message>
        <source>RES_MENU_PAGE</source>
        <translation>Page Edit</translation>
    </message>
    <message>
        <source>RES_MENU_PAGEDELETE</source>
        <translation>Delete</translation>
    </message>
    <message>
        <source>RES_MENU_PAGEMOVEFORWARD</source>
        <translation>Move Forward</translation>
    </message>
    <message>
        <source>RES_MENU_PAGEMOVEBACKWARD</source>
        <translation>Move Backward</translation>
    </message>
    <message>
        <source>RES_MENU_PREFERENCES</source>
        <translation>Preferências</translation>
    </message>
    <message>
        <source>RES_MENU_HELP</source>
        <translation>Ajuda</translation>
    </message>
    <message>
        <source>RES_MENU_ABOUT</source>
        <translation>Sobre</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_ADD</source>
        <translation>Add Annotation</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_VIEW</source>
        <translation>View/Edit Annotation</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_DELETE</source>
        <translation>Delete Annotation</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_SAVE</source>
        <translation>Save Annotations</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_SHOW</source>
        <translation>Show Annotations</translation>
    </message>
    <message>
        <source>RES_MENU_ANNOTATE_HIDE</source>
        <translation>Hide Annotations</translation>
    </message>
    <message>
        <source>RES_TITLE_GOTOPAGE</source>
        <translation>Ir para Página</translation>
    </message>
    <message>
        <source>RES_HINT_GOTOPAGE</source>
        <translation>Página Número:</translation>
    </message>
    <message>
        <source>RES_TITLE_GOTOELEMENT</source>
        <translation>Ir para Elemento</translation>
    </message>
    <message>
        <source>RES_HINT_GOTOELEMENT</source>
        <translation>ID de Elemento, ex: "F5":</translation>
    </message>
    <message>
        <source>RES_TITLE_SEARCH</source>
        <translation>Pesquisar</translation>
    </message>
    <message>
        <source>RES_HINT_SEARCH</source>
        <translation>Pesquisar linha:</translation>
    </message>
    <message>
        <source>RES_TITLE_PASSWORD</source>
        <translation>Insira senha</translation>
    </message>
    <message>
        <source>RES_HINT_PASSWORD</source>
        <translation>Senha:</translation>
    </message>
    <message>
        <source>RES_OK</source>
        <translation>OK</translation>
    </message>
    <message>
        <source>RES_OPEN</source>
        <translation>Abrir</translation>
    </message>
    <message>
        <source>RES_YES</source>
        <translation>Sim</translation>
    </message>
    <message>
        <source>RES_NO</source>
        <translation>Não</translation>
    </message>
    <message>
        <source>RES_CANCEL</source>
        <translation>Cancelar</translation>
    </message>
    <message>
        <source>RES_FULLSCREEN</source>
        <translation>Tela inteira</translation>
    </message>
    <message>
        <source>RES_MEMORY_HEAP_KB</source>
        <translation>8192</translation>
    </message>
</context>
<context>
    <name>PrefDialog</name>
    <message>
        <source>RES_PREF_CAPTION</source>
        <translation>Preferências</translation>
    </message>
    <message>
        <source>RES_PREF_SINGLEPAGE</source>
        <translation>Carregar página por página</translation>
    </message>
    <message>
        <source>RES_PREF_CHARENCODING</source>
        <translation>Configurar Caractere</translation>
    </message>
    <message>
        <source>RES_PREF_DEFENCODING</source>
        <translation>Padrão</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO88591</source>
        <translation>Oeste (ISO 8859-1)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_BIG5</source>
        <translation>Chinês Tradicional (Grande 5)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_GBK</source>
        <translation>Chinês Simplificado (GBK)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_SHIFTJIS</source>
        <translation>Japonês (SHIFT JIS)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO2022JP</source>
        <translation>Japonês (ISO 2022-JP)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_EUCJP</source>
        <translation>Japonês (EUC-JP)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_WINDOWS949</source>
        <translation>Coreano (Windows CP 949)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_UTF8</source>
        <translation>Universal (UTF-8)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_WINDOWS1251</source>
        <translation>Windows (Windows CP 1251)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_KOI8</source>
        <translation>Cirílico (KOI-8)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_WINDOWS866</source>
        <translation>DOS (Windows CP 866)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO88595</source>
        <translation>Cirílico (ISO 8859-5)</translation>
    </message>
    <message>
        <source>RES_PREF_ENCODING_ISO88597</source>
        <translation>Grego (ISO 8859-7)</translation>
    </message>
    <message>
        <source>RES_PREF_AUTOENCODING</source>
        <translation>Detectar automaticamente</translation>
    </message>
    <message>
        <source>RES_PREF_BASIC</source>
        <translation>Basic</translation>
    </message>
    <message>
        <source>RES_PREF_OTHER</source>
        <translation>Other</translation>
    </message>
    <message>
        <source>RES_PREF_MORE_PREFERENCES</source>
        <translation>More preferences...</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_PREFERENCES</source>
        <translation>OEM Preferences</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_NAME</source>
        <translation>Name</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_VALUE</source>
        <translation>Value</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_RESTART_WARNING</source>
        <translation>The application needs to be restarted before OEM preference changes can take effect.  Restart now?</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_PREF_FONT_COULD_NOT_BE_REGISTERED</source>
        <translation>Error: A font enabled in fileviewer.cfg could not be registered. Please check which languages are defined in the project make file.</translation>
    </message>
    <message>
        <source>RES_PREF_OEM_PREF_FILE_NOT_FOUND</source>
        <translation>The fileviewer.cfg preferences file cannot be found in the current working directory. Preferences may not function correctly.</translation>
    </message>
</context>
<context>
    <name>HelpDialog</name>
    <message>
        <source>RES_HELP_CAPTION</source>
        <translation>Ajudar Picsel Viewer</translation>
    </message>
    <message>
        <source>RES_HELP_UNKNOWN</source>
        <translation>Desconhecido</translation>
    </message>
</context>
<context>
    <name>AboutDialog</name>
    <message>
        <source>RES_ABOUT_CAPTION</source>
        <translation>Sobre Picsel Viewer</translation>
    </message>
    <message>
        <source>RES_ABOUT_UNKNOWN</source>
        <translation>Desconhecido</translation>
    </message>
    <message>
        <source>RES_ABOUTWOMARKUP_PART0</source>
        <translation>Picsel Viewer</translation>
    </message>
    <message>
        <source>RES_ABOUTWOMARKUP_PART1</source>
        <translation>(Issue </translation>
    </message>
    <message>
        <source>RES_ABOUTWOMARKUP_PART2</source>
        <translation>)</translation>
    </message>
    <message>
        <source>RES_ABOUT_PART0</source>
        <translation><![CDATA[<qt><h3>Picsel Viewer&trade;.</h3><em>Version ]]></translation>
    </message>
    <message>
        <source>RES_ABOUT_PART1</source>
        <translation> (Issue </translation>
    </message>
    <message>
        <source>RES_ABOUT_PART2</source>
        <translation><![CDATA[)</em><p><font size=2><p><p>Powered by Picsel ePAGE&reg; technology.<br>Copyright &copy; Picsel 2000-2008.  All rights reserved.<p><hr>This computer program, user interface and design are protected by international, US and European copyright laws. US and international Patents applied for. Picsel, Picsel Viewer, ePAGE and the Picsel cube logo are trademarks or registered trademarks of Picsel Technologies Ltd.<p><p>This version of the Picsel Viewer has been licensed only for use by ]]></translation>
    </message>
    <message>
        <source>RES_ABOUT_PART3</source>
        <translation><![CDATA[.<p><hr><h4>Acknowledgements</h4><p>This software is based in part on the work of the independent JPEG group. <p>String library &copy; 1999-2000 Ralf S. Engelschall rse@engelschall.com.<p>This product includes software developed by the Apache Group for use in the Apache HTTP server project (http://www.apache.org/).<p>Parts of this software are derived from the RSA Data Security, Inc. MD5 Message-Digest Algorithm.<p>LZW decoder for GIF, &copy; 1987, by Steven A. Bennett.<p>'C' functions Copyright &copy; 1988, 1993 The Regents of the University of California.</qt>]]></translation>
    </message>
</context>
<context>
    <name>DirDialog</name>
    <message>
        <source>RES_DIR_CAPTION</source>
        <translation>Diretório</translation>
    </message>
    <message>
        <source>RES_DIR_UNKNOWN</source>
        <translation>Desconhecido</translation>
    </message>
</context>
<context>
    <name>Core</name>
    <message>
        <source>RES_ALERT_DOCTRANSLATIONFAILED</source>
        <translation>O aplicativo não pode exibir este arquivo</translation>
    </message>
    <message>
        <source>RES_ALERT_INTERNALERROR</source>
        <translation>Erro Interno</translation>
    </message>
    <message>
        <source>RES_ALERT_OUTOFMEMORY</source>
        <translation>Sem Memória</translation>
    </message>
    <message>
        <source>RES_ALERT_UNKNOWNERROR</source>
        <translation>Ocorreu um erro desconhecido</translation>
    </message>
    <message>
        <source>RES_ALERT_DOCSAVEDSUCCESSFULLY</source>
        <translation>Documento salvo</translation>
    </message>
    <message>
        <source>RES_ALERT_DOCSAVEERROR</source>
        <translation>Ocorreu um erro ao salvar</translation>
    </message>
    <message>
        <source>RES_ALERT_SEARCHERROR</source>
        <translation>Buscar erro</translation>
    </message>
    <message>
        <source>RES_ALERT_SEARCHFAILED</source>
        <translation>Busca falhou - não encontrada</translation>
    </message>
    <message>
        <source>RES_ALERT_SEARCHWRAPPED</source>
        <translation>Busca concluída - continuar?</translation>
    </message>
    <message>
        <source>RES_ALERT_GOTOFAILED</source>
        <translation>Ir para falha - elemento não encontrado</translation>
    </message>
    <message>
        <source>RES_ALERT_GOTOERROR</source>
        <translation>Ir para falha</translation>
    </message>
    <message>
        <source>RES_ALERT_NOTHINGSELECTED</source>
        <translation>Não selecionou nada</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTOEDIT</source>
        <translation>Falha ao editar esta seleção</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTODELETE</source>
        <translation>Falha ao excluir</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTOINSERT</source>
        <translation>Falha ao inserir</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTOUPDATE</source>
        <translation>Falha ao atualizar documento</translation>
    </message>
    <message>
        <source>RES_ALERT_COULDNOTINSERTHERE</source>
        <translation>Não foi possível inserir aqui</translation>
    </message>
    <message>
        <source>RES_ALERT_COULDNOTINSERTMAX</source>
        <translation>Não foi possível inserir - tamanho máximo do documento</translation>
    </message>
    <message>
        <source>RES_ALERT_FAILEDTODESELECT</source>
        <translation>Falha ao desmarcar. Tente novamente ou recarregue o documento.</translation>
    </message>
    <message>
        <source>RES_ALERT_INVALIDFONTSIZE</source>
        <translation>Tamanho da fonte inválido. Tamanhos válidos são 2-144 pt</translation>
    </message>
    <message>
        <source>RES_ALERT_INVALIDFORMATSTRING</source>
        <translation>Formato de linha especificado inválido</translation>
    </message>
    <message>
        <source>RES_ALERT_DOCNOTEDITABLE</source>
        <translation>Não é possível editar documento</translation>
    </message>
    <message>
        <source>RES_ALERT_ERRORINFORMULA</source>
        <translation>Erro na fórmula</translation>
    </message>
    <message>
        <source>RES_ALERT_FORMULAUNSUPPORTED</source>
        <translation>Fórmula não suportada</translation>
    </message>
    <message>
        <source>RES_ALERT_CIRCULARDEPENDENCY</source>
        <translation>Dependência circular foi encontrada em fórmula</translation>
    </message>
    <message>
        <source>RES_ALERT_ARRAYNOTSUPPORTED</source>
        <translation>Não é possível atualizar fórmula da tabela ou disposição.</translation>
    </message>
    <message>
        <source>RES_ALERT_SORTFAILED</source>
        <translation>Sorting has failed</translation>
    </message>
    <message>
        <source>RES_ALERT_INVALIDGOTO</source>
        <translation>O valor especificado não parece ser um local de célula válido</translation>
    </message>
    <message>
        <source>RES_ALERT_FORMULASUNSUPPORTED</source>
        <translation>O documento contem fórmulas não suportadas pelo Picsel.
Não é possível editá-lo.</translation>
    </message>
    <message>
        <source>RES_ALERT_IMAGESUBSAMPLED</source>
        <translation>Images within the document have been subsampled to conserve memory</translation>
    </message>
    <message>
        <source>RES_ALERT_TABLERESTRICTION</source>
        <translation>Row/column insertion/deletion is not allowed within a table or pivot table</translation>
    </message>
    <message>
        <source>RES_ALERT_ANNOTATION_SAVED</source>
        <translation>Annotations have been saved</translation>
    </message>
    <message>
        <source>RES_CONFIRM_ANNOTATION_LOAD</source>
        <translation>Annotation file found.  Load it?</translation>
    </message>
    <message>
        <source>RES_CONFIRM_OPENNEW</source>
        <translation>O documento foi editado.
Deseja realmente abrir este documento e perder os dados editados?</translation>
    </message>
    <message>
        <source>RES_CONFIRM_CONFIRMQUIT</source>
        <translation>O documento foi editado.
Deseja realmente sair e perder os dados editados?</translation>
    </message>
    <message>
        <source>RES_CONFIRM_CONTENTLOSS</source>
        <translation>O documento original não está presente, se salvar o documento agora, imagens serão perdidas.
Continuar?</translation>
    </message>
</context>
</TS>
